{
  "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
  "repository_url": "https://api.github.com/repos/ethereum-optimism/optimism",
  "labels_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500/comments",
  "events_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500/events",
  "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500",
  "id": 1498868563,
  "node_id": "I_kwDODjvEJM5ZVutT",
  "number": 4500,
  "title": "Getting \"nonce too low\" after restarting l2geth",
  "user": {
    "login": "sanbotto",
    "id": 28357728,
    "node_id": "MDQ6VXNlcjI4MzU3NzI4",
    "avatar_url": "https://avatars.githubusercontent.com/u/28357728?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sanbotto",
    "html_url": "https://github.com/sanbotto",
    "followers_url": "https://api.github.com/users/sanbotto/followers",
    "following_url": "https://api.github.com/users/sanbotto/following{/other_user}",
    "gists_url": "https://api.github.com/users/sanbotto/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sanbotto/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sanbotto/subscriptions",
    "organizations_url": "https://api.github.com/users/sanbotto/orgs",
    "repos_url": "https://api.github.com/users/sanbotto/repos",
    "events_url": "https://api.github.com/users/sanbotto/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sanbotto/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 2907832490,
      "node_id": "MDU6TGFiZWwyOTA3ODMyNDkw",
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/labels/C-bug",
      "name": "C-bug",
      "color": "C5DEF5",
      "default": false,
      "description": "Category: This is a bug."
    },
    {
      "id": 2981541772,
      "node_id": "MDU6TGFiZWwyOTgxNTQxNzcy",
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/labels/P-confirmed",
      "name": "P-confirmed",
      "color": "BFD4F2",
      "default": false,
      "description": "A confirmed bug"
    },
    {
      "id": 3357535896,
      "node_id": "MDU6TGFiZWwzMzU3NTM1ODk2",
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/labels/M-l2geth",
      "name": "M-l2geth",
      "color": "FBCA04",
      "default": false,
      "description": "Module: l2geth"
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 9,
  "created_at": "2022-12-15T18:03:11Z",
  "updated_at": "2023-04-07T09:42:49Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "**Describe the bug**\r\nl2geth breaks after restarting it. l2geth is working perfectly fine, I restart it and then this shows up in the logs:\r\n\r\n```\r\nINFO [12-15|16:59:29.673] Syncing transaction batch range          start=43668 end=48186\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769274\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769275\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769276\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769277\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769278\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769279\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769280\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769281\r\nERROR[12-15|16:59:29.681] Mismatched transaction                   index=5769282\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769283\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769284\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769285\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769286\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769287\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769288\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769289\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769290\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769291\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769292\r\nERROR[12-15|16:59:29.682] Mismatched transaction                   index=5769293\r\nERROR[12-15|16:59:29.682] Problem committing transaction           msg=\"nonce too low\"\r\nERROR[12-15|16:59:29.682] Got error waiting for transaction to be added to chain msg=\"nonce too low\"\r\nERROR[12-15|16:59:29.682] Could not verify                         error=\"Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: nonce too low\"\r\n```\r\n\r\n&#x200B;\r\n\r\n**To Reproduce**\r\n1. Create a new node following the non-Docker configuration described [here](https://community.optimism.io/docs/developers/build/run-a-node/#non-docker-configuration).\r\n2. Create unit files for DTL and l2geth (see code bellow).\r\n3. Start DTL and l2geth by running the following:\r\n    ```\r\n    systemctl daemon-reload\r\n    systemctl start optimism-dtl\r\n    systemctl start optimism-l2geth\r\n    ```\r\n4. Restart l2geth with:\r\n    ```\r\n    systemctl restart optimism-l2geth\r\n    ```\r\n\r\n&#x200B;\r\n\r\n**Expected behavior**\r\nl2geth should continue working properly after restarting it.\r\n\r\n&#x200B;\r\n\r\n**System Specs:**\r\n - OS: Ubuntu 20.04.5 LTS\r\n - Kernel: Linux 5.15.0-1026-aws\r\n - vCPUs: 4\r\n - RAM: 16GB\r\n - Disk: 1500GiB\r\n - Commit hash: af2cf449d1081e85ba346565d343ed7737871e75\r\n\r\n&#x200B;\r\n\r\n**Additional context**\r\nEvery now and then, my Optimism nodes completely break and I have to recreate them from scratch and wait about 6 days for them to sync again. Now, I realize that I can't even safely restart the node without breaking it. I'm not sure if this is a bug or if I'm doing something wrong, but I'm pretty sure that this is not the expected behavior because it's highly unstable.\r\n\r\nIf this instability can't be fixed, I welcome a way to recover nodes from backups. I've tried all sorts of DR solutions but, given that a service restart breaks l2geth, restoring never works since a service restart is implied.\r\n\r\n&#x200B;\r\n\r\n**Env and config files**\r\n\r\nDTL's `.env`:\r\n\r\n```\r\nDATA_TRANSPORT_LAYER__NODE_ENV=production\r\nDATA_TRANSPORT_LAYER__ETH_NETWORK_NAME=mainnet\r\nDATA_TRANSPORT_LAYER__DB_PATH=/chaindata/optimism/packages/data-transport-layer/db\r\nDATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0xdE1FCfB0851916CA5101820A69b13a4E276bd81F\r\nDATA_TRANSPORT_LAYER__POLLING_INTERVAL=5000\r\nDATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true\r\nDATA_TRANSPORT_LAYER__CONFIRMATIONS=12\r\nDATA_TRANSPORT_LAYER__SERVER_HOSTNAME=localhost\r\nDATA_TRANSPORT_LAYER__SERVER_PORT=7878\r\nDATA_TRANSPORT_LAYER__SYNC_FROM_L1=true\r\nDATA_TRANSPORT_LAYER__DEFAULT_BACKEND=l1\r\nDATA_TRANSPORT_LAYER__L1_GAS_PRICE_BACKEND=l1\r\nDATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=https://mainnet.infura.io/v3/REDACTED_KEY\r\nDATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=2000\r\nDATA_TRANSPORT_LAYER__SYNC_FROM_L2=false\r\nDATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://optimism-mainnet.infura.io/v3/REDACTED_KEY\r\nDATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000\r\nDATA_TRANSPORT_LAYER__L2_CHAIN_ID=10\r\nDATA_TRANSPORT_LAYER__LEGACY_SEQUENCER_COMPATIBILITY=false\r\n```\r\n\r\nDTL's unit file (`optimism-dtl.service`):\r\n\r\n```\r\n[Unit]\r\nDescription = Optimism's Data Transport Layer\r\nAfter       = network.target\r\nRequires    = network.target\r\n\r\n[Service]\r\nUser             = root\r\nWorkingDirectory = /chaindata/optimism/packages/data-transport-layer\r\nExecStart        = yarn start\r\nStandardOutput   = file:/var/log/optimism/dtl.log\r\nStandardError    = file:/var/log/optimism/dtl-error.log\r\nRestart          = on-failure\r\nRestartSec       = 5\r\nTimeoutStartSec  = 20\r\nTimeoutStopSec   = 20\r\n\r\n[Install]\r\nWantedBy = multi-user.target\r\n```\r\n\r\nl2geth's unit file (`optimism-l2geth.service`):\r\n\r\n```\r\n\r\n[Unit]\r\nDescription = Optimism's L2 Geth\r\nAfter       = network.target\r\nRequires    = network.target\r\n\r\n[Service]\r\nEnvironment=CHAIN_ID=10\r\nEnvironment=DATADIR=/chaindata/optimism/l2geth/gethData\r\nEnvironment=NETWORK_ID=10\r\nEnvironment=NO_DISCOVER=true\r\nEnvironment=NO_USB=true\r\nEnvironment=GASPRICE=0\r\nEnvironment=GCMODE=full\r\nEnvironment=BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F\r\nEnvironment=BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27\r\nEnvironment=ETH1_CTC_DEPLOYMENT_HEIGHT=13596466\r\nEnvironment=ETH1_SYNC_SERVICE_ENABLE=true\r\nEnvironment=ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A\r\nEnvironment=ROLLUP_BACKEND=l1\r\nEnvironment=ROLLUP_CLIENT_HTTP=http://localhost:7878\r\nEnvironment=ROLLUP_DISABLE_TRANSFERS=false\r\nEnvironment=ROLLUP_ENABLE_L2_GAS_POLLING=false\r\nEnvironment=ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159\r\nEnvironment=ROLLUP_MAX_CALLDATA_SIZE=40000\r\nEnvironment=ROLLUP_POLL_INTERVAL_FLAG=1s\r\nEnvironment=ROLLUP_SYNC_SERVICE_ENABLE=true\r\nEnvironment=ROLLUP_TIMESTAMP_REFRESH=5m\r\nEnvironment=ROLLUP_VERIFIER_ENABLE=true\r\nEnvironment=RPC_ADDR=0.0.0.0\r\nEnvironment=RPC_API=eth,rollup,net,web3,debug\r\nEnvironment=RPC_CORS_DOMAIN=*\r\nEnvironment=RPC_ENABLE=true\r\nEnvironment=RPC_PORT=8545\r\nEnvironment=RPC_VHOSTS=*\r\nEnvironment=SEQUENCER_CLIENT_HTTP=https://optimism-mainnet.infura.io/v3/REDACTED_KEY\r\nEnvironment=TARGET_GAS_LIMIT=15000000\r\nEnvironment=USING_OVM=true\r\nEnvironment=WS_ADDR=0.0.0.0\r\nEnvironment=WS_API=eth,rollup,net,web3,debug\r\nEnvironment=WS_ORIGINS=*\r\nEnvironment=WS=true\r\n\r\nUser      = root\r\nExecStart = /chaindata/optimism/l2geth/build/bin/geth \\\r\n  --datadir=$DATADIR \\\r\n  --password=$DATADIR/password \\\r\n  --allow-insecure-unlock \\\r\n  --unlock=$BLOCK_SIGNER_ADDRESS \\\r\n  --mine \\\r\n  --miner.etherbase=$BLOCK_SIGNER_ADDRESS\r\n\r\nStandardOutput  = file:/var/log/optimism/l2geth.log\r\nStandardError   = file:/var/log/optimism/l2geth-error.log\r\nRestart         = on-failure\r\nRestartSec      = 5\r\nTimeoutStartSec = 20\r\nTimeoutStopSec  = 20\r\n\r\n[Install]\r\nWantedBy = multi-user.target\r\n```",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500/reactions",
    "total_count": 3,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 3
  },
  "timeline_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1379869119",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1379869119",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1379869119,
    "node_id": "IC_kwDODjvEJM5SPyG_",
    "user": {
      "login": "vlad-she",
      "id": 16667906,
      "node_id": "MDQ6VXNlcjE2NjY3OTA2",
      "avatar_url": "https://avatars.githubusercontent.com/u/16667906?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vlad-she",
      "html_url": "https://github.com/vlad-she",
      "followers_url": "https://api.github.com/users/vlad-she/followers",
      "following_url": "https://api.github.com/users/vlad-she/following{/other_user}",
      "gists_url": "https://api.github.com/users/vlad-she/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vlad-she/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vlad-she/subscriptions",
      "organizations_url": "https://api.github.com/users/vlad-she/orgs",
      "repos_url": "https://api.github.com/users/vlad-she/repos",
      "events_url": "https://api.github.com/users/vlad-she/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vlad-she/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-12T06:22:53Z",
    "updated_at": "2023-01-12T06:22:53Z",
    "author_association": "NONE",
    "body": "I run a new node today, started syncing it from scratch\r\nand getting the same error\r\n\r\n@sanbotto have you found a solution or workaround???",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1379869119/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1380936095",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1380936095",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1380936095,
    "node_id": "IC_kwDODjvEJM5ST2mf",
    "user": {
      "login": "sanbotto",
      "id": 28357728,
      "node_id": "MDQ6VXNlcjI4MzU3NzI4",
      "avatar_url": "https://avatars.githubusercontent.com/u/28357728?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sanbotto",
      "html_url": "https://github.com/sanbotto",
      "followers_url": "https://api.github.com/users/sanbotto/followers",
      "following_url": "https://api.github.com/users/sanbotto/following{/other_user}",
      "gists_url": "https://api.github.com/users/sanbotto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sanbotto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sanbotto/subscriptions",
      "organizations_url": "https://api.github.com/users/sanbotto/orgs",
      "repos_url": "https://api.github.com/users/sanbotto/repos",
      "events_url": "https://api.github.com/users/sanbotto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sanbotto/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-12T20:02:24Z",
    "updated_at": "2023-01-12T20:02:24Z",
    "author_association": "NONE",
    "body": "> I run a new node today, started syncing it from scratch and getting the same error\r\n> \r\n> @sanbotto have you found a solution or workaround???\r\n\r\nSadly, I haven't.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1380936095/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1385385447",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1385385447",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1385385447,
    "node_id": "IC_kwDODjvEJM5Sk03n",
    "user": {
      "login": "dnldd",
      "id": 1281030,
      "node_id": "MDQ6VXNlcjEyODEwMzA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1281030?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dnldd",
      "html_url": "https://github.com/dnldd",
      "followers_url": "https://api.github.com/users/dnldd/followers",
      "following_url": "https://api.github.com/users/dnldd/following{/other_user}",
      "gists_url": "https://api.github.com/users/dnldd/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dnldd/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dnldd/subscriptions",
      "organizations_url": "https://api.github.com/users/dnldd/orgs",
      "repos_url": "https://api.github.com/users/dnldd/repos",
      "events_url": "https://api.github.com/users/dnldd/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dnldd/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-17T12:57:05Z",
    "updated_at": "2023-01-17T12:57:05Z",
    "author_association": "NONE",
    "body": "Having the same issue here, resynced twice already as a result. Some feedback from the team would be great.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1385385447/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1398824868",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1398824868",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1398824868,
    "node_id": "IC_kwDODjvEJM5TYF-k",
    "user": {
      "login": "kaladinlight",
      "id": 35275952,
      "node_id": "MDQ6VXNlcjM1Mjc1OTUy",
      "avatar_url": "https://avatars.githubusercontent.com/u/35275952?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kaladinlight",
      "html_url": "https://github.com/kaladinlight",
      "followers_url": "https://api.github.com/users/kaladinlight/followers",
      "following_url": "https://api.github.com/users/kaladinlight/following{/other_user}",
      "gists_url": "https://api.github.com/users/kaladinlight/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kaladinlight/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kaladinlight/subscriptions",
      "organizations_url": "https://api.github.com/users/kaladinlight/orgs",
      "repos_url": "https://api.github.com/users/kaladinlight/repos",
      "events_url": "https://api.github.com/users/kaladinlight/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kaladinlight/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-20T19:14:59Z",
    "updated_at": "2023-01-20T19:16:01Z",
    "author_association": "NONE",
    "body": "Will just add that I have been having the same issue as well. I have redundant nodes and have been needing to frequently snapshot to restore when this occurs. It seems random and related to ungraceful shutdown and inability of the node to recover gracefully. Hoping op-geth and bedrock upgrade will resolve many of the sync/restart issues that I have been plagued with on l2-geth :crossed_fingers: ",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1398824868/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1398899116",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1398899116",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1398899116,
    "node_id": "IC_kwDODjvEJM5TYYGs",
    "user": {
      "login": "sanbotto",
      "id": 28357728,
      "node_id": "MDQ6VXNlcjI4MzU3NzI4",
      "avatar_url": "https://avatars.githubusercontent.com/u/28357728?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sanbotto",
      "html_url": "https://github.com/sanbotto",
      "followers_url": "https://api.github.com/users/sanbotto/followers",
      "following_url": "https://api.github.com/users/sanbotto/following{/other_user}",
      "gists_url": "https://api.github.com/users/sanbotto/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sanbotto/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sanbotto/subscriptions",
      "organizations_url": "https://api.github.com/users/sanbotto/orgs",
      "repos_url": "https://api.github.com/users/sanbotto/repos",
      "events_url": "https://api.github.com/users/sanbotto/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sanbotto/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-20T20:32:39Z",
    "updated_at": "2023-01-20T20:32:39Z",
    "author_association": "NONE",
    "body": "> snapshot to restore\r\n\r\nHow are you doing that? I haven't been able to recover a node using any form of backup, neither with full volume snapshots nor with [these publicly available snapshots](https://archive.org/download/optimism-snapshot) of just `dtl` and `l2geth`.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1398899116/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1399051723",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1399051723",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1399051723,
    "node_id": "IC_kwDODjvEJM5TY9XL",
    "user": {
      "login": "kaladinlight",
      "id": 35275952,
      "node_id": "MDQ6VXNlcjM1Mjc1OTUy",
      "avatar_url": "https://avatars.githubusercontent.com/u/35275952?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kaladinlight",
      "html_url": "https://github.com/kaladinlight",
      "followers_url": "https://api.github.com/users/kaladinlight/followers",
      "following_url": "https://api.github.com/users/kaladinlight/following{/other_user}",
      "gists_url": "https://api.github.com/users/kaladinlight/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kaladinlight/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kaladinlight/subscriptions",
      "organizations_url": "https://api.github.com/users/kaladinlight/orgs",
      "repos_url": "https://api.github.com/users/kaladinlight/repos",
      "events_url": "https://api.github.com/users/kaladinlight/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kaladinlight/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-20T23:02:42Z",
    "updated_at": "2023-01-20T23:02:42Z",
    "author_association": "NONE",
    "body": "> > snapshot to restore\r\n> \r\n> How are you doing that? I haven't been able to recover a node using any form of backup, neither with full volume snapshots nor with [these publicly available snapshots](https://archive.org/download/optimism-snapshot) of just `dtl` and `l2geth`.\r\n\r\nMy infrastructure is deployed on aws, so I am just using ebs volume snapshots after shutting down the node and hoping the shutdown was graceful and I got a healthy snapshot. With a healthy snapshot, I have been able to successfully recreate a volume from the snapshot and mount to my running instance in order to spin back up. I have not tried any of the public snapshot images myself.\r\n\r\nDo you see this error condition when spinning back up from a full volume snapshot? What version of l2geth are you running? I feel like there may have been a marginal stability improvement on l2geth v0.5.30, which noted some graceful shutdown improvements, but obviously didn't fix the problem.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1399051723/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1420176550",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1420176550",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1420176550,
    "node_id": "IC_kwDODjvEJM5Upiym",
    "user": {
      "login": "smartcontracts",
      "id": 14298799,
      "node_id": "MDQ6VXNlcjE0Mjk4Nzk5",
      "avatar_url": "https://avatars.githubusercontent.com/u/14298799?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smartcontracts",
      "html_url": "https://github.com/smartcontracts",
      "followers_url": "https://api.github.com/users/smartcontracts/followers",
      "following_url": "https://api.github.com/users/smartcontracts/following{/other_user}",
      "gists_url": "https://api.github.com/users/smartcontracts/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smartcontracts/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smartcontracts/subscriptions",
      "organizations_url": "https://api.github.com/users/smartcontracts/orgs",
      "repos_url": "https://api.github.com/users/smartcontracts/repos",
      "events_url": "https://api.github.com/users/smartcontracts/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smartcontracts/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-02-07T04:16:24Z",
    "updated_at": "2023-02-07T04:16:24Z",
    "author_association": "CONTRIBUTOR",
    "body": "Sorry for the delay here. Team has been heads down on the Bedrock release and some l2geth maintenance has slipped through the cracks. `Mismatched transaction` is an obvious indicator that something is going wrong. Going to ask around tomorrow to figure out what might be happening here and see if we can get a release out. \r\n\r\nApologies again for the delay and very much appreciate your patience 🙏 ",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1420176550/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 1,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1438312905",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1438312905",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1438312905,
    "node_id": "IC_kwDODjvEJM5VuunJ",
    "user": {
      "login": "Ekzer",
      "id": 13622449,
      "node_id": "MDQ6VXNlcjEzNjIyNDQ5",
      "avatar_url": "https://avatars.githubusercontent.com/u/13622449?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ekzer",
      "html_url": "https://github.com/Ekzer",
      "followers_url": "https://api.github.com/users/Ekzer/followers",
      "following_url": "https://api.github.com/users/Ekzer/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ekzer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ekzer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ekzer/subscriptions",
      "organizations_url": "https://api.github.com/users/Ekzer/orgs",
      "repos_url": "https://api.github.com/users/Ekzer/repos",
      "events_url": "https://api.github.com/users/Ekzer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ekzer/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-02-21T11:23:45Z",
    "updated_at": "2023-02-21T11:23:45Z",
    "author_association": "NONE",
    "body": "Hi, any news please? We are stuck with this problem too :( ",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1438312905/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1500125978",
    "html_url": "https://github.com/ethereum-optimism/optimism/issues/4500#issuecomment-1500125978",
    "issue_url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/4500",
    "id": 1500125978,
    "node_id": "IC_kwDODjvEJM5Zahsa",
    "user": {
      "login": "bimlas",
      "id": 7034200,
      "node_id": "MDQ6VXNlcjcwMzQyMDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7034200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bimlas",
      "html_url": "https://github.com/bimlas",
      "followers_url": "https://api.github.com/users/bimlas/followers",
      "following_url": "https://api.github.com/users/bimlas/following{/other_user}",
      "gists_url": "https://api.github.com/users/bimlas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bimlas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bimlas/subscriptions",
      "organizations_url": "https://api.github.com/users/bimlas/orgs",
      "repos_url": "https://api.github.com/users/bimlas/repos",
      "events_url": "https://api.github.com/users/bimlas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bimlas/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-04-07T09:42:48Z",
    "updated_at": "2023-04-07T09:42:48Z",
    "author_association": "NONE",
    "body": "@smartcontracts, is it solwed?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum-optimism/optimism/issues/comments/1500125978/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
