{
  "url": "https://api.github.com/repos/ConsenSys/teku/issues/5738",
  "repository_url": "https://api.github.com/repos/ConsenSys/teku",
  "labels_url": "https://api.github.com/repos/ConsenSys/teku/issues/5738/labels{/name}",
  "comments_url": "https://api.github.com/repos/ConsenSys/teku/issues/5738/comments",
  "events_url": "https://api.github.com/repos/ConsenSys/teku/issues/5738/events",
  "html_url": "https://github.com/ConsenSys/teku/issues/5738",
  "id": 1265073147,
  "node_id": "I_kwDOCM9I9M5LZ3v7",
  "number": 5738,
  "title": "Ropsten Merge - loss of websockets connection",
  "user": {
    "login": "benjaminion",
    "id": 20796281,
    "node_id": "MDQ6VXNlcjIwNzk2Mjgx",
    "avatar_url": "https://avatars.githubusercontent.com/u/20796281?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/benjaminion",
    "html_url": "https://github.com/benjaminion",
    "followers_url": "https://api.github.com/users/benjaminion/followers",
    "following_url": "https://api.github.com/users/benjaminion/following{/other_user}",
    "gists_url": "https://api.github.com/users/benjaminion/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/benjaminion/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/benjaminion/subscriptions",
    "organizations_url": "https://api.github.com/users/benjaminion/orgs",
    "repos_url": "https://api.github.com/users/benjaminion/repos",
    "events_url": "https://api.github.com/users/benjaminion/events{/privacy}",
    "received_events_url": "https://api.github.com/users/benjaminion/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "zilm13",
    "id": 6196452,
    "node_id": "MDQ6VXNlcjYxOTY0NTI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/6196452?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zilm13",
    "html_url": "https://github.com/zilm13",
    "followers_url": "https://api.github.com/users/zilm13/followers",
    "following_url": "https://api.github.com/users/zilm13/following{/other_user}",
    "gists_url": "https://api.github.com/users/zilm13/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zilm13/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zilm13/subscriptions",
    "organizations_url": "https://api.github.com/users/zilm13/orgs",
    "repos_url": "https://api.github.com/users/zilm13/repos",
    "events_url": "https://api.github.com/users/zilm13/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zilm13/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "zilm13",
      "id": 6196452,
      "node_id": "MDQ6VXNlcjYxOTY0NTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6196452?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zilm13",
      "html_url": "https://github.com/zilm13",
      "followers_url": "https://api.github.com/users/zilm13/followers",
      "following_url": "https://api.github.com/users/zilm13/following{/other_user}",
      "gists_url": "https://api.github.com/users/zilm13/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zilm13/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zilm13/subscriptions",
      "organizations_url": "https://api.github.com/users/zilm13/orgs",
      "repos_url": "https://api.github.com/users/zilm13/repos",
      "events_url": "https://api.github.com/users/zilm13/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zilm13/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2022-06-08T17:25:27Z",
  "updated_at": "2022-06-20T11:30:58Z",
  "closed_at": "2022-06-20T11:30:58Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "A user reports the following.\r\n\r\n`teku v22.5.2 + geth v1.10.18`\r\n\r\nShortly before the Merge, we had an issue connecting teku to geth via Websockets. Our configuration looked like this:\r\n\r\n```\r\nTEKU_EE_ENDPOINT=ws://localhost:8551\r\n```\r\n\r\nAnd we were getting the following output:\r\n\r\n```\r\n2022-06-08 14:36:24.100 ERROR - Unexpected error while checking TTD\r\njava.util.concurrent.CompletionException: org.java_websocket.exceptions.WebsocketNotConnectedException\r\nat java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]\r\nat java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]\r\nat\r\njava.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141) ~[?:?]\r\nat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]\r\nat tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:145) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]\r\nat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]\r\nat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]\r\nat\r\njava.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]\r\nat java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]\r\nCaused by: org.java_websocket.exceptions.WebsocketNotConnectedException\r\nat org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:664) ~[Java-WebSocket-1.5.2.jar:?]\r\nat org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:640) ~[Java-WebSocket-1.5.2.jar:?]\r\nat org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:431) ~[Java-WebSocket-1.5.2.jar:?]\r\nat org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:234) ~[core-4.9.1.jar:?]\r\nat org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:185) ~[core-4.9.1.jar:?]\r\nat org.web3j.protocol.core.Request.sendAsync(Request.java:91) ~[core-4.9.1.jar:?]\r\nat tech.pegasys.teku.ethereum.executionclient.web3j.Web3JExecutionEngineClient.getPowChainHead(Web3JExecutionEngineClient.java:68) ~[teku-ethereum-executionclient-22.5.2.jar:22.5.2]\r\nat tech.pegasys.teku.ethereum.executionclient.ThrottlingExecutionEngineClient.lambda$getPowChainHead$1(ThrottlingExecutionEngineClient.java:56) ~[teku-ethereum-executionclient-22.5.2.jar:22.5.2]\r\nat tech.pegasys.teku.infrastructure.async.ThrottlingTaskQueue.lambda$queueTask$0(ThrottlingTaskQueue.java:42) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]\r\nat tech.pegasys.teku.infrastructure.async.ThrottlingTaskQueue.processQueuedTasks(ThrottlingTaskQueue.java:58) ~[teku-infrastructure-async-22.5.2.jar:22.5.2]\r\n```\r\n\r\nChanging to http resolved the issue: `TEKU_EE_ENDPOINT=http://localhost:8551/`\r\n\r\nAfter the Merge, Websockets started working again and we were unable to reproduce the issue.\r\n\r\n",
  "closed_by": {
    "login": "zilm13",
    "id": 6196452,
    "node_id": "MDQ6VXNlcjYxOTY0NTI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/6196452?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zilm13",
    "html_url": "https://github.com/zilm13",
    "followers_url": "https://api.github.com/users/zilm13/followers",
    "following_url": "https://api.github.com/users/zilm13/following{/other_user}",
    "gists_url": "https://api.github.com/users/zilm13/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zilm13/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zilm13/subscriptions",
    "organizations_url": "https://api.github.com/users/zilm13/orgs",
    "repos_url": "https://api.github.com/users/zilm13/repos",
    "events_url": "https://api.github.com/users/zilm13/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zilm13/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/5738/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ConsenSys/teku/issues/5738/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1150586716",
    "html_url": "https://github.com/ConsenSys/teku/issues/5738#issuecomment-1150586716",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/5738",
    "id": 1150586716,
    "node_id": "IC_kwDOCM9I9M5ElI9c",
    "user": {
      "login": "rolfyone",
      "id": 2967240,
      "node_id": "MDQ6VXNlcjI5NjcyNDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2967240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rolfyone",
      "html_url": "https://github.com/rolfyone",
      "followers_url": "https://api.github.com/users/rolfyone/followers",
      "following_url": "https://api.github.com/users/rolfyone/following{/other_user}",
      "gists_url": "https://api.github.com/users/rolfyone/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rolfyone/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rolfyone/subscriptions",
      "organizations_url": "https://api.github.com/users/rolfyone/orgs",
      "repos_url": "https://api.github.com/users/rolfyone/repos",
      "events_url": "https://api.github.com/users/rolfyone/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rolfyone/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-06-09T01:55:55Z",
    "updated_at": "2022-06-09T01:55:55Z",
    "author_association": "CONTRIBUTOR",
    "body": "It'd be good to get the logs if they're still accessible...\n\n - did they say \"Execution Client is offline\" in logs\n - did anything happen to the eth1 client (like a restart?)\n - was it prolonged or a one-off\n\nthe exception itself is because a request was made that failed to complete, but to determine if there's value in altering the output, we'd be able to reason better with a lot more context... as a default, reporting the exception trace is giving us context that we wouldn't have otherwise in this instance...",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1150586716/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1151287058",
    "html_url": "https://github.com/ConsenSys/teku/issues/5738#issuecomment-1151287058",
    "issue_url": "https://api.github.com/repos/ConsenSys/teku/issues/5738",
    "id": 1151287058,
    "node_id": "IC_kwDOCM9I9M5Enz8S",
    "user": {
      "login": "zilm13",
      "id": 6196452,
      "node_id": "MDQ6VXNlcjYxOTY0NTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6196452?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zilm13",
      "html_url": "https://github.com/zilm13",
      "followers_url": "https://api.github.com/users/zilm13/followers",
      "following_url": "https://api.github.com/users/zilm13/following{/other_user}",
      "gists_url": "https://api.github.com/users/zilm13/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zilm13/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zilm13/subscriptions",
      "organizations_url": "https://api.github.com/users/zilm13/orgs",
      "repos_url": "https://api.github.com/users/zilm13/repos",
      "events_url": "https://api.github.com/users/zilm13/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zilm13/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-06-09T15:34:10Z",
    "updated_at": "2022-06-09T15:55:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "I have one idea what it could be, will try to reproduce when current task is finished.\r\nOur connection was dropped by occasion, but flag `connected` kept true, and there is no strategy to reconnect in this case",
    "reactions": {
      "url": "https://api.github.com/repos/ConsenSys/teku/issues/comments/1151287058/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
