{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/17590",
  "id": 357278471,
  "node_id": "MDU6SXNzdWUzNTcyNzg0NzE=",
  "number": 17590,
  "title": "traceBlock aborts if a sender can't afford gas",
  "user": {
    "login": "emile",
    "id": 30124,
    "node_id": "MDQ6VXNlcjMwMTI0",
    "avatar_url": "https://avatars.githubusercontent.com/u/30124?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/emile",
    "html_url": "https://github.com/emile",
    "followers_url": "https://api.github.com/users/emile/followers",
    "following_url": "https://api.github.com/users/emile/following{/other_user}",
    "gists_url": "https://api.github.com/users/emile/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/emile/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/emile/subscriptions",
    "organizations_url": "https://api.github.com/users/emile/orgs",
    "repos_url": "https://api.github.com/users/emile/repos",
    "events_url": "https://api.github.com/users/emile/events{/privacy}",
    "received_events_url": "https://api.github.com/users/emile/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2018-09-05T15:16:37Z",
  "updated_at": "2019-02-01T09:31:15Z",
  "closed_at": "2019-02-01T09:31:15Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "The trace results from all other transactions in a block are currently discarded if any fail with an \"insufficient balance to pay for gas\" error. It should be possible to trace all non-failing transactions in a block using traceBlock, even if some of them fail the state transition precheck.\r\n\r\n#### System information\r\n\r\nGeth version: 1.8.15-stable\r\nOS & Version: Linux\r\n\r\n#### Expected behaviour\r\n```\r\n[{result: {failed: false, ...}},\r\n {result: {failed: false, ...}},\r\n {result: {failed: true, ...}}]\r\n```\r\nor \r\n```\r\n [{result: {failed: false, ...}},\r\n  {result: {failed: false, ...}},\r\n  {error: \"tracing failed: insufficient balance to pay for gas\"}]\r\n``` \r\n#### Actual behaviour\r\n```\r\nError: insufficient balance to pay for gas\r\n    at web3.js:3143:20\r\n    at web3.js:6347:15\r\n    at web3.js:5081:36\r\n    at <anonymous>:1:1\r\n```\r\n#### Steps to reproduce the behaviour\r\ndebug.traceBlockByNumber(\"0xDFCA7\")\r\ndebug.traceBlockByNumber(\"0x1777C0\")\r\ndebug.traceBlockByNumber(\"0x19D845\")\r\ndebug.traceBlockByNumber(\"0x282C18\")",
  "closed_by": {
    "login": "holiman",
    "id": 142290,
    "node_id": "MDQ6VXNlcjE0MjI5MA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/142290?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/holiman",
    "html_url": "https://github.com/holiman",
    "followers_url": "https://api.github.com/users/holiman/followers",
    "following_url": "https://api.github.com/users/holiman/following{/other_user}",
    "gists_url": "https://api.github.com/users/holiman/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/holiman/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/holiman/subscriptions",
    "organizations_url": "https://api.github.com/users/holiman/orgs",
    "repos_url": "https://api.github.com/users/holiman/repos",
    "events_url": "https://api.github.com/users/holiman/events{/privacy}",
    "received_events_url": "https://api.github.com/users/holiman/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/419034812",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/17590#issuecomment-419034812",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590",
    "id": 419034812,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQxOTAzNDgxMg==",
    "user": {
      "login": "begelundmuller",
      "id": 791356,
      "node_id": "MDQ6VXNlcjc5MTM1Ng==",
      "avatar_url": "https://avatars.githubusercontent.com/u/791356?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/begelundmuller",
      "html_url": "https://github.com/begelundmuller",
      "followers_url": "https://api.github.com/users/begelundmuller/followers",
      "following_url": "https://api.github.com/users/begelundmuller/following{/other_user}",
      "gists_url": "https://api.github.com/users/begelundmuller/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/begelundmuller/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/begelundmuller/subscriptions",
      "organizations_url": "https://api.github.com/users/begelundmuller/orgs",
      "repos_url": "https://api.github.com/users/begelundmuller/repos",
      "events_url": "https://api.github.com/users/begelundmuller/events{/privacy}",
      "received_events_url": "https://api.github.com/users/begelundmuller/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-09-06T09:51:37Z",
    "updated_at": "2018-09-06T09:51:37Z",
    "author_association": "NONE",
    "body": "I also just bumped into this issue, specifically for blocks 916647 and 1693765. However, according to Etherscan, no transactions in these had errors. \r\n\r\nI'm also using `debug.traceBlockByNumber`.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/419034812/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/451253194",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/17590#issuecomment-451253194",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590",
    "id": 451253194,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MTI1MzE5NA==",
    "user": {
      "login": "Eric-Showers",
      "id": 24963520,
      "node_id": "MDQ6VXNlcjI0OTYzNTIw",
      "avatar_url": "https://avatars.githubusercontent.com/u/24963520?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eric-Showers",
      "html_url": "https://github.com/Eric-Showers",
      "followers_url": "https://api.github.com/users/Eric-Showers/followers",
      "following_url": "https://api.github.com/users/Eric-Showers/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eric-Showers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eric-Showers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eric-Showers/subscriptions",
      "organizations_url": "https://api.github.com/users/Eric-Showers/orgs",
      "repos_url": "https://api.github.com/users/Eric-Showers/repos",
      "events_url": "https://api.github.com/users/Eric-Showers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eric-Showers/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-01-03T19:36:56Z",
    "updated_at": "2019-01-03T19:36:56Z",
    "author_association": "NONE",
    "body": "Hi just encountered this error while tracing block `916647` as well.\r\n\r\nRequest:\r\n`{\r\n\t\"jsonrpc\": \"2.0\",\r\n\t\"method\": \"debug_traceBlockByNumber\",\r\n\t\"params\": [\r\n\t\t\"0xDFCA7\",\r\n\t\t{\r\n\t\t\t\"tracer\": \"callTracer\"\r\n\t\t}\r\n\t],\r\n\t\"id\": 74\r\n}`\r\nResponse:\r\n`{\r\n  \"jsonrpc\": \"2.0\",\r\n  \"id\": 74,\r\n  \"error\": {\r\n    \"code\": -32000,\r\n    \"message\": \"insufficient balance to pay for gas\"\r\n  }\r\n}`\r\n\r\nWhat is most interesting however, is that of the 3 transactions in this block Geth is still able to trace two of them properly. The following two tx hashes return a normal response from `debug_traceTransaction`:\r\n`0x44e4f29f592e42cd1a104dc7347c02c78ac7a66be6e42005d2ad32f7b4f63218`\r\n`0x4a5718d38238e2674208b0f0b95a6016ffe2b3002d11b464eaffefad79cf1c08`\r\n\r\nHere is the problematic tx in the block:\r\nRequest:\r\n`{\r\n\t\"jsonrpc\": \"2.0\",\r\n\t\"method\": \"debug_traceTransaction\",\r\n\t\"params\": [\r\n\t\t\"0xca879fcf2d0146fc4e214ed5d9747a2743b6a586b4f1de1541e52c2fe6be5bad\",\r\n\t\t{\r\n\t\t\t\"tracer\": \"callTracer\"\r\n\t\t}\r\n\t],\r\n\t\"id\": 74\r\n}`\r\nResponse:\r\n`{\r\n  \"jsonrpc\": \"2.0\",\r\n  \"id\": 74,\r\n  \"error\": {\r\n    \"code\": -32000,\r\n    \"message\": \"tracing failed: insufficient balance to pay for gas\"\r\n  }\r\n}`",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/451253194/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/451253653",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/17590#issuecomment-451253653",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/17590",
    "id": 451253653,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MTI1MzY1Mw==",
    "user": {
      "login": "Eric-Showers",
      "id": 24963520,
      "node_id": "MDQ6VXNlcjI0OTYzNTIw",
      "avatar_url": "https://avatars.githubusercontent.com/u/24963520?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eric-Showers",
      "html_url": "https://github.com/Eric-Showers",
      "followers_url": "https://api.github.com/users/Eric-Showers/followers",
      "following_url": "https://api.github.com/users/Eric-Showers/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eric-Showers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eric-Showers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eric-Showers/subscriptions",
      "organizations_url": "https://api.github.com/users/Eric-Showers/orgs",
      "repos_url": "https://api.github.com/users/Eric-Showers/repos",
      "events_url": "https://api.github.com/users/Eric-Showers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eric-Showers/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-01-03T19:38:41Z",
    "updated_at": "2019-01-03T19:38:41Z",
    "author_association": "NONE",
    "body": "As far as I understand, performing a trace of any of those three transactions requires tracing the entire block anyways. So how come Geth only returns an error when tracing the problematic tx or explicitly tracing the whole block?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/451253653/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
