{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25491",
  "id": 1330976100,
  "node_id": "I_kwDOAOvK985PVRVk",
  "number": 25491,
  "title": "Geth not start bind: address already in use",
  "user": {
    "login": "Piradoxlanieve",
    "id": 10765838,
    "node_id": "MDQ6VXNlcjEwNzY1ODM4",
    "avatar_url": "https://avatars.githubusercontent.com/u/10765838?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Piradoxlanieve",
    "html_url": "https://github.com/Piradoxlanieve",
    "followers_url": "https://api.github.com/users/Piradoxlanieve/followers",
    "following_url": "https://api.github.com/users/Piradoxlanieve/following{/other_user}",
    "gists_url": "https://api.github.com/users/Piradoxlanieve/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Piradoxlanieve/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Piradoxlanieve/subscriptions",
    "organizations_url": "https://api.github.com/users/Piradoxlanieve/orgs",
    "repos_url": "https://api.github.com/users/Piradoxlanieve/repos",
    "events_url": "https://api.github.com/users/Piradoxlanieve/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Piradoxlanieve/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 72233650,
      "node_id": "MDU6TGFiZWw3MjIzMzY1MA==",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:bug",
      "name": "type:bug",
      "color": "FF5E5E",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 4,
  "created_at": "2022-08-07T10:30:42Z",
  "updated_at": "2022-08-12T07:55:55Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "#### System information\r\n\r\nGeth version: `Geth/v1.10.21-stable-67109427/linux-amd64/go1.18.4`\r\nOS & Version: Ubuntu 20.04.4\r\n\r\nHi. I had my geth node working perfectly, I restarted the pc and now I have this error\r\n\r\n```\r\nago 07 12:09:46 nodoeth geth[11482]: WARN [08-07|12:09:46.352] IPC opening failed url=/mnt/ssd/geth.ipc error=\"listen unix /mnt/ssd/geth.ipc: bind: address already in use\"\r\n\r\nago 07 12:09:47 nodoeth geth[11482]: Fatal: Error starting protocol stack: listen unix /mnt/ssd/geth.ipc: bind: address already in use\r\n\r\nago 07 12:09:47 nodoeth systemd[1]: eth1.service: Main process exited, code=exited, status=1/FAILURE\r\n\r\nago 07 12:09:47 nodoeth systemd[1]: eth1.service: Failed with result 'exit-code'.\r\n\r\nago 07 12:09:48 nodoeth systemd[1]: Stopped geth execution client service.\r\n\r\n```\r\n```\r\nroot@nodoeth:/mnt/ssd# ps ax | grep geth\r\n\r\n11893 pts/2 S+ 0:00 grep --color=auto geth\r\n\r\nroot@nodoeth:/mnt/ssd#\r\n```\r\n\r\nthe only solution I find is to change the geth directory and re-synchronize or also --ipcdisable but I don't know what affects this flag. Any ideas. I've been several hours and I don't see what address is using geth.ipc\r\n\r\nSorry my bad english.",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1207887781",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25491#issuecomment-1207887781",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491",
    "id": 1207887781,
    "node_id": "IC_kwDOAOvK985H_uel",
    "user": {
      "login": "karalabe",
      "id": 129561,
      "node_id": "MDQ6VXNlcjEyOTU2MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/129561?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/karalabe",
      "html_url": "https://github.com/karalabe",
      "followers_url": "https://api.github.com/users/karalabe/followers",
      "following_url": "https://api.github.com/users/karalabe/following{/other_user}",
      "gists_url": "https://api.github.com/users/karalabe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karalabe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karalabe/subscriptions",
      "organizations_url": "https://api.github.com/users/karalabe/orgs",
      "repos_url": "https://api.github.com/users/karalabe/repos",
      "events_url": "https://api.github.com/users/karalabe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karalabe/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-08T09:31:26Z",
    "updated_at": "2022-08-08T09:31:26Z",
    "author_association": "MEMBER",
    "body": "Unsure what it could be. Perhaps you could check to make sure the SSD is mounted with the proper permissions? Haven't seen this issue until now. Perhaps you could try deleting the socket file `/mnt/ssd/geth.ipc` and restarting your machine. Can't imagine what is off, but I'd guess some permission somewhere.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1207887781/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1207902042",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25491#issuecomment-1207902042",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491",
    "id": 1207902042,
    "node_id": "IC_kwDOAOvK985H_x9a",
    "user": {
      "login": "Piradoxlanieve",
      "id": 10765838,
      "node_id": "MDQ6VXNlcjEwNzY1ODM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/10765838?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Piradoxlanieve",
      "html_url": "https://github.com/Piradoxlanieve",
      "followers_url": "https://api.github.com/users/Piradoxlanieve/followers",
      "following_url": "https://api.github.com/users/Piradoxlanieve/following{/other_user}",
      "gists_url": "https://api.github.com/users/Piradoxlanieve/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Piradoxlanieve/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Piradoxlanieve/subscriptions",
      "organizations_url": "https://api.github.com/users/Piradoxlanieve/orgs",
      "repos_url": "https://api.github.com/users/Piradoxlanieve/repos",
      "events_url": "https://api.github.com/users/Piradoxlanieve/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Piradoxlanieve/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-08T09:45:42Z",
    "updated_at": "2022-08-08T09:45:42Z",
    "author_association": "NONE",
    "body": "Yes, before opening the error I tried to delete geth.ipc, give it 777 permissions, but without success, I also looked to see if it was a port in use but there was nothing, I had never had that error, it has been very rare.\r\n I think it's some locked file inside the chaindata folder, maybe manifest, lock, current file, because when they were renamed the SSD started working at 400mb/s but I prefer to generate everything again.\r\n I have decided to delete the entire folder and re-synchronize snap again, maybe if I had changed the location without deleting the files, but well it's too late.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1207902042/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1209028290",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25491#issuecomment-1209028290",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491",
    "id": 1209028290,
    "node_id": "IC_kwDOAOvK985IEE7C",
    "user": {
      "login": "ligi",
      "id": 111600,
      "node_id": "MDQ6VXNlcjExMTYwMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/111600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ligi",
      "html_url": "https://github.com/ligi",
      "followers_url": "https://api.github.com/users/ligi/followers",
      "following_url": "https://api.github.com/users/ligi/following{/other_user}",
      "gists_url": "https://api.github.com/users/ligi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ligi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ligi/subscriptions",
      "organizations_url": "https://api.github.com/users/ligi/orgs",
      "repos_url": "https://api.github.com/users/ligi/repos",
      "events_url": "https://api.github.com/users/ligi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ligi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-09T07:42:24Z",
    "updated_at": "2022-08-09T07:42:24Z",
    "author_association": "MEMBER",
    "body": "next time this happens: can you do a `lsof | grep \"geth.ipc\"` ?",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1209028290/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1212835144",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25491#issuecomment-1212835144",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25491",
    "id": 1212835144,
    "node_id": "IC_kwDOAOvK985ISmVI",
    "user": {
      "login": "ekawibisono",
      "id": 22586872,
      "node_id": "MDQ6VXNlcjIyNTg2ODcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/22586872?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ekawibisono",
      "html_url": "https://github.com/ekawibisono",
      "followers_url": "https://api.github.com/users/ekawibisono/followers",
      "following_url": "https://api.github.com/users/ekawibisono/following{/other_user}",
      "gists_url": "https://api.github.com/users/ekawibisono/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ekawibisono/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ekawibisono/subscriptions",
      "organizations_url": "https://api.github.com/users/ekawibisono/orgs",
      "repos_url": "https://api.github.com/users/ekawibisono/repos",
      "events_url": "https://api.github.com/users/ekawibisono/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ekawibisono/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-12T07:55:55Z",
    "updated_at": "2022-08-12T07:55:55Z",
    "author_association": "NONE",
    "body": "hello,\r\nThis is the same problem as me, but this problem has been resolved, please click this link\r\n> https://github.com/ethereum/go-ethereum/issues/25438#issuecomment-1199434922",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1212835144/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
