{
  "url": "https://api.github.com/repos/ethereum/py-evm/issues/1877",
  "repository_url": "https://api.github.com/repos/ethereum/py-evm",
  "labels_url": "https://api.github.com/repos/ethereum/py-evm/issues/1877/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/py-evm/issues/1877/comments",
  "events_url": "https://api.github.com/repos/ethereum/py-evm/issues/1877/events",
  "html_url": "https://github.com/ethereum/py-evm/issues/1877",
  "id": 526134124,
  "node_id": "MDU6SXNzdWU1MjYxMzQxMjQ=",
  "number": 1877,
  "title": "Bug: py-evm delays ice age in Istanbul, but no such delay is scheduled",
  "user": {
    "login": "carver",
    "id": 205327,
    "node_id": "MDQ6VXNlcjIwNTMyNw==",
    "avatar_url": "https://avatars.githubusercontent.com/u/205327?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/carver",
    "html_url": "https://github.com/carver",
    "followers_url": "https://api.github.com/users/carver/followers",
    "following_url": "https://api.github.com/users/carver/following{/other_user}",
    "gists_url": "https://api.github.com/users/carver/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/carver/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/carver/subscriptions",
    "organizations_url": "https://api.github.com/users/carver/orgs",
    "repos_url": "https://api.github.com/users/carver/repos",
    "events_url": "https://api.github.com/users/carver/events{/privacy}",
    "received_events_url": "https://api.github.com/users/carver/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2019-11-20T19:55:33Z",
  "updated_at": "2019-11-20T21:54:32Z",
  "closed_at": "2019-11-20T21:54:32Z",
  "author_association": "MEMBER",
  "active_lock_reason": null,
  "body": "Thanks to @veox for raising the issue (twice) in gitter.\r\n\r\nThis is the offending line, which should stay at the petersburg definition (of 5M)\r\nhttps://github.com/ethereum/py-evm/blob/c83815a22c6ff23429ed32165a79c5e41577ef64/eth/vm/forks/istanbul/headers.py#L8",
  "closed_by": {
    "login": "carver",
    "id": 205327,
    "node_id": "MDQ6VXNlcjIwNTMyNw==",
    "avatar_url": "https://avatars.githubusercontent.com/u/205327?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/carver",
    "html_url": "https://github.com/carver",
    "followers_url": "https://api.github.com/users/carver/followers",
    "following_url": "https://api.github.com/users/carver/following{/other_user}",
    "gists_url": "https://api.github.com/users/carver/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/carver/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/carver/subscriptions",
    "organizations_url": "https://api.github.com/users/carver/orgs",
    "repos_url": "https://api.github.com/users/carver/repos",
    "events_url": "https://api.github.com/users/carver/events{/privacy}",
    "received_events_url": "https://api.github.com/users/carver/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/py-evm/issues/1877/reactions",
    "total_count": 1,
    "+1": 0,
    "-1": 0,
    "laugh": 1,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/py-evm/issues/1877/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[

]
