{
  "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
  "repository_url": "https://api.github.com/repos/ChainSafe/lodestar",
  "labels_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243/labels{/name}",
  "comments_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243/comments",
  "events_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243/events",
  "html_url": "https://github.com/ChainSafe/lodestar/issues/4243",
  "id": 1294846132,
  "node_id": "I_kwDOCD5_Gc5NLci0",
  "number": 4243,
  "title": "`Static key doesn't match to peer that signed payload` error on connection in hive docker",
  "user": {
    "login": "marioevz",
    "id": 11726710,
    "node_id": "MDQ6VXNlcjExNzI2NzEw",
    "avatar_url": "https://avatars.githubusercontent.com/u/11726710?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/marioevz",
    "html_url": "https://github.com/marioevz",
    "followers_url": "https://api.github.com/users/marioevz/followers",
    "following_url": "https://api.github.com/users/marioevz/following{/other_user}",
    "gists_url": "https://api.github.com/users/marioevz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/marioevz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/marioevz/subscriptions",
    "organizations_url": "https://api.github.com/users/marioevz/orgs",
    "repos_url": "https://api.github.com/users/marioevz/repos",
    "events_url": "https://api.github.com/users/marioevz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/marioevz/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 1200090447,
      "node_id": "MDU6TGFiZWwxMjAwMDkwNDQ3",
      "url": "https://api.github.com/repos/ChainSafe/lodestar/labels/prio-high",
      "name": "prio-high",
      "color": "fd9579",
      "default": false,
      "description": "Resolve issues as soon as possible."
    },
    {
      "id": 2155825090,
      "node_id": "MDU6TGFiZWwyMTU1ODI1MDkw",
      "url": "https://api.github.com/repos/ChainSafe/lodestar/labels/scope-networking",
      "name": "scope-networking",
      "color": "980043",
      "default": false,
      "description": "All issues related to networking, gossip, and libp2p."
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": {
    "login": "wemeetagain",
    "id": 1348242,
    "node_id": "MDQ6VXNlcjEzNDgyNDI=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1348242?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/wemeetagain",
    "html_url": "https://github.com/wemeetagain",
    "followers_url": "https://api.github.com/users/wemeetagain/followers",
    "following_url": "https://api.github.com/users/wemeetagain/following{/other_user}",
    "gists_url": "https://api.github.com/users/wemeetagain/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/wemeetagain/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wemeetagain/subscriptions",
    "organizations_url": "https://api.github.com/users/wemeetagain/orgs",
    "repos_url": "https://api.github.com/users/wemeetagain/repos",
    "events_url": "https://api.github.com/users/wemeetagain/events{/privacy}",
    "received_events_url": "https://api.github.com/users/wemeetagain/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "wemeetagain",
      "id": 1348242,
      "node_id": "MDQ6VXNlcjEzNDgyNDI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1348242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wemeetagain",
      "html_url": "https://github.com/wemeetagain",
      "followers_url": "https://api.github.com/users/wemeetagain/followers",
      "following_url": "https://api.github.com/users/wemeetagain/following{/other_user}",
      "gists_url": "https://api.github.com/users/wemeetagain/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wemeetagain/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wemeetagain/subscriptions",
      "organizations_url": "https://api.github.com/users/wemeetagain/orgs",
      "repos_url": "https://api.github.com/users/wemeetagain/repos",
      "events_url": "https://api.github.com/users/wemeetagain/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wemeetagain/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": null,
  "comments": 7,
  "created_at": "2022-07-05T22:26:51Z",
  "updated_at": "2023-01-23T16:20:18Z",
  "closed_at": "2023-01-23T16:20:17Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "**Describe the bug**\r\nLodestar fails to connect with bootnode peer in hive docker environment (using https://github.com/ethereum/hive/pull/577).\r\n\r\nThe second node fails to connect with the following error:\r\n```\r\nJul-05 20:10:30.478[NETWORK]         \u001B[34mdebug\u001B[39m: Error dialing discovered peer peer=16...wncgtg Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Static key doesn't match to peer that signed payload!\r\nAggregateError: Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Static key doesn't match to peer that signed payload!\r\n    at maybeSettle (/usr/app/node_modules/p-some/index.js:31:11)\r\n    at /usr/app/node_modules/p-some/index.js:69:23\r\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\r\n```\r\n\r\nENR is collected from the boot node from the `/eth/v1/node/identity` endpoint, and appended as command line argument for the second node:\r\nhttps://github.com/marioevz/hive/blob/f345b86a6df51ff32e66f8b0e58d24b7df7ae574/clients/lodestar-bn/lodestar_bn.sh#L37\r\n\r\n**Expected behavior**\r\nBoth nodes should be connected to perform the test.\r\n\r\n**Steps to Reproduce**\r\n\r\nUse https://github.com/marioevz/hive/tree/client-lodestar branch to run the `eth2/engine` hive simulator:\r\n```\r\n./hive --client go-ethereum,lodestar-bn,lodestar-vc --sim eth2/engine --sim.loglevel 5\r\n```\r\n\r\n**Desktop (please complete the following information):**\r\n\r\n- OS: Ubuntu\r\n- Version: 18.04.6 LTS (Bionic Beaver)\r\n- Branch: v0.40.0-dev.0b4c4bf39a\r\n- Commit hash: 0b4c4bf39a6b54f0bdaaef924e67788c35d10d6e\r\n",
  "closed_by": {
    "login": "dapplion",
    "id": 35266934,
    "node_id": "MDQ6VXNlcjM1MjY2OTM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dapplion",
    "html_url": "https://github.com/dapplion",
    "followers_url": "https://api.github.com/users/dapplion/followers",
    "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
    "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
    "organizations_url": "https://api.github.com/users/dapplion/orgs",
    "repos_url": "https://api.github.com/users/dapplion/repos",
    "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dapplion/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1176028771",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4243#issuecomment-1176028771",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
    "id": 1176028771,
    "node_id": "IC_kwDOCD5_Gc5GGMZj",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-07-06T09:59:18Z",
    "updated_at": "2022-07-06T10:04:11Z",
    "author_association": "MEMBER",
    "body": "@mpetrunic could you comment in what situations Lodestar may throw this error? Why could the bootnode keypair wrong? I'm not familiar with noise internals\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1176028771/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1176034469",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4243#issuecomment-1176034469",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
    "id": 1176034469,
    "node_id": "IC_kwDOCD5_Gc5GGNyl",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-07-06T10:05:21Z",
    "updated_at": "2022-07-06T10:06:09Z",
    "author_association": "MEMBER",
    "body": "Error is decorated here\r\n\r\n`Error: Error occurred during XX handshake`: \r\n- https://github.com/ChainSafe/js-libp2p-noise/blob/1e3d20738c90d68133011a59bb5054138ee9e2b5/src/noise.ts#L195\r\n\r\n`Error occurred while verifying signed payload`: one of this three places, which one?\r\n- https://github.com/ChainSafe/js-libp2p-noise/blob/1e3d20738c90d68133011a59bb5054138ee9e2b5/src/handshake-xx.ts#L103\r\n- https://github.com/ChainSafe/js-libp2p-noise/blob/1e3d20738c90d68133011a59bb5054138ee9e2b5/src/handshake-xx.ts#L138\r\n- https://github.com/ChainSafe/js-libp2p-noise/blob/1e3d20738c90d68133011a59bb5054138ee9e2b5/src/handshake-xx-fallback.ts#L78\r\n\r\n`Static key doesn't match to peer that signed payload!`\r\n- https://github.com/ChainSafe/js-libp2p-noise/blob/1e3d20738c90d68133011a59bb5054138ee9e2b5/src/utils.ts#L104",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1176034469/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1180805663",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4243#issuecomment-1180805663",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
    "id": 1180805663,
    "node_id": "IC_kwDOCD5_Gc5GYaof",
    "user": {
      "login": "mpetrunic",
      "id": 8836210,
      "node_id": "MDQ6VXNlcjg4MzYyMTA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8836210?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mpetrunic",
      "html_url": "https://github.com/mpetrunic",
      "followers_url": "https://api.github.com/users/mpetrunic/followers",
      "following_url": "https://api.github.com/users/mpetrunic/following{/other_user}",
      "gists_url": "https://api.github.com/users/mpetrunic/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mpetrunic/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mpetrunic/subscriptions",
      "organizations_url": "https://api.github.com/users/mpetrunic/orgs",
      "repos_url": "https://api.github.com/users/mpetrunic/repos",
      "events_url": "https://api.github.com/users/mpetrunic/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mpetrunic/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-07-11T19:54:27Z",
    "updated_at": "2022-07-11T19:54:27Z",
    "author_association": "MEMBER",
    "body": "Already wrote on discord couple of days ago. Pretty sure its not related to noise. Could be lodestar messing with peerId in libp2p",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1180805663/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1183294151",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4243#issuecomment-1183294151",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
    "id": 1183294151,
    "node_id": "IC_kwDOCD5_Gc5Gh6LH",
    "user": {
      "login": "wemeetagain",
      "id": 1348242,
      "node_id": "MDQ6VXNlcjEzNDgyNDI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1348242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wemeetagain",
      "html_url": "https://github.com/wemeetagain",
      "followers_url": "https://api.github.com/users/wemeetagain/followers",
      "following_url": "https://api.github.com/users/wemeetagain/following{/other_user}",
      "gists_url": "https://api.github.com/users/wemeetagain/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wemeetagain/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wemeetagain/subscriptions",
      "organizations_url": "https://api.github.com/users/wemeetagain/orgs",
      "repos_url": "https://api.github.com/users/wemeetagain/repos",
      "events_url": "https://api.github.com/users/wemeetagain/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wemeetagain/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-07-13T14:25:35Z",
    "updated_at": "2022-07-13T14:26:08Z",
    "author_association": "MEMBER",
    "body": "I've also seen this occasionally (8 times in a ~24hr period) in #4114 \r\n\r\nThe stack trace seems a little more helpful now tho\r\n\r\n```\r\n2022-07-11T16:57:34.734Z libp2p:upgrader:error Failed to upgrade outbound connection UnexpectedPeerError: Error occurred during XX handshake: Error occurred while verifying signed payload: Static key doesn't match to peer that signed payload!\r\n    at XXHandshake.exchange (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/handshake-xx.ts:103:15)\r\n    at runMicrotasks (<anonymous>)\r\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\r\n    at Noise.performXXHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:220:7)\r\n    at Noise.performHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:165:14)\r\n    at Noise.secureOutbound (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:75:23)\r\n    at EventTarget._encryptOutbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:541:12)\r\n    at EventTarget.upgradeOutbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:248:11)\r\n    at TCP.dial (file:///home/cayman/Code/lodestar/node_modules/@libp2p/tcp/src/index.ts:37:18)\r\n    at EventTarget.dial (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/transport-manager.ts:115:14) {\r\n  code: 'ERR_ENCRYPTION_FAILED'\r\n}\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1183294151/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 1
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1183299001",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4243#issuecomment-1183299001",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
    "id": 1183299001,
    "node_id": "IC_kwDOCD5_Gc5Gh7W5",
    "user": {
      "login": "wemeetagain",
      "id": 1348242,
      "node_id": "MDQ6VXNlcjEzNDgyNDI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1348242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wemeetagain",
      "html_url": "https://github.com/wemeetagain",
      "followers_url": "https://api.github.com/users/wemeetagain/followers",
      "following_url": "https://api.github.com/users/wemeetagain/following{/other_user}",
      "gists_url": "https://api.github.com/users/wemeetagain/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wemeetagain/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wemeetagain/subscriptions",
      "organizations_url": "https://api.github.com/users/wemeetagain/orgs",
      "repos_url": "https://api.github.com/users/wemeetagain/repos",
      "events_url": "https://api.github.com/users/wemeetagain/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wemeetagain/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-07-13T14:29:40Z",
    "updated_at": "2022-07-13T14:29:40Z",
    "author_association": "MEMBER",
    "body": "also seeing hundreds / thousands of this similar-ish stack trace\r\n```\r\n2022-07-12T04:13:30.447Z libp2p:upgrader:error Failed to upgrade outbound connection UnexpectedPeerError: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.    at XXHandshake.exchange (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/handshake-xx.ts:103:15)\r\n    at runMicrotasks (<anonymous>) \r\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\r\n    at Noise.performXXHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:220:7)\r\n    at Noise.performHandshake (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:165:14)\r\n    at Noise.secureOutbound (file:///home/cayman/Code/lodestar/node_modules/@chainsafe/libp2p-noise/src/noise.ts:75:23)\r\n    at EventTarget._encryptOutbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:541:12)\r\n    at EventTarget.upgradeOutbound (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/upgrader.ts:248:11)\r\n    at TCP.dial (file:///home/cayman/Code/lodestar/node_modules/@libp2p/tcp/src/index.ts:37:18)\r\n    at EventTarget.dial (file:///home/cayman/Code/lodestar/node_modules/libp2p/src/transport-manager.ts:115:14) {\r\n  code: 'ERR_ENCRYPTION_FAILED'\r\n}\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1183299001/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1183531691",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4243#issuecomment-1183531691",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
    "id": 1183531691,
    "node_id": "IC_kwDOCD5_Gc5Gi0Kr",
    "user": {
      "login": "wemeetagain",
      "id": 1348242,
      "node_id": "MDQ6VXNlcjEzNDgyNDI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1348242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wemeetagain",
      "html_url": "https://github.com/wemeetagain",
      "followers_url": "https://api.github.com/users/wemeetagain/followers",
      "following_url": "https://api.github.com/users/wemeetagain/following{/other_user}",
      "gists_url": "https://api.github.com/users/wemeetagain/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wemeetagain/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wemeetagain/subscriptions",
      "organizations_url": "https://api.github.com/users/wemeetagain/orgs",
      "repos_url": "https://api.github.com/users/wemeetagain/repos",
      "events_url": "https://api.github.com/users/wemeetagain/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wemeetagain/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-07-13T18:13:38Z",
    "updated_at": "2022-07-13T18:13:38Z",
    "author_association": "MEMBER",
    "body": "So this second error \"Peer ID doesn't match...\" happens when establishing an outbound connection, we're passing in a peer id during handshake initialization that differs from the one thats discovered during the handshake. (Maybe like dialing a discovered ENR to a node that's rebooted and generated a new peer id).\r\n\r\nNot sure yet about the \"Static key doesn't match...\". It seems we create the remote static key initialized to a zeroed Uint8Array, and it should get set here https://github.com/ChainSafe/js-libp2p-noise/blob/master/src/handshakes/xx.ts#L91. I'd guess in these error cases, its not getting set there.",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1183531691/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1400620396",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4243#issuecomment-1400620396",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4243",
    "id": 1400620396,
    "node_id": "IC_kwDOCD5_Gc5Te8Vs",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-01-23T16:20:17Z",
    "updated_at": "2023-01-23T16:20:17Z",
    "author_association": "MEMBER",
    "body": "Lodestar successfully runs in Hive tests for withdrawals",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1400620396/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 1,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
