{
  "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
  "repository_url": "https://api.github.com/repos/ChainSafe/lodestar",
  "labels_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763/labels{/name}",
  "comments_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763/comments",
  "events_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763/events",
  "html_url": "https://github.com/ChainSafe/lodestar/issues/4763",
  "id": 1446651872,
  "node_id": "I_kwDOCD5_Gc5WOifg",
  "number": 4763,
  "title": "getUpdates function of lightclient no longer works",
  "user": {
    "login": "jtguibas",
    "id": 25734765,
    "node_id": "MDQ6VXNlcjI1NzM0NzY1",
    "avatar_url": "https://avatars.githubusercontent.com/u/25734765?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jtguibas",
    "html_url": "https://github.com/jtguibas",
    "followers_url": "https://api.github.com/users/jtguibas/followers",
    "following_url": "https://api.github.com/users/jtguibas/following{/other_user}",
    "gists_url": "https://api.github.com/users/jtguibas/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jtguibas/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jtguibas/subscriptions",
    "organizations_url": "https://api.github.com/users/jtguibas/orgs",
    "repos_url": "https://api.github.com/users/jtguibas/repos",
    "events_url": "https://api.github.com/users/jtguibas/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jtguibas/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 7,
  "created_at": "2022-11-12T23:50:52Z",
  "updated_at": "2023-05-29T07:26:41Z",
  "closed_at": "2023-05-29T07:26:41Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "<!--NOTE: -->\r\n<!--- General questions should go to the discord chat instead of the issue tracker.-->\r\n\r\nCalling the endpoint https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1 no longer works.\r\n\r\n<!--A clear and concise description of what the bug is and steps to reproduce it.-->\r\n\r\nSimply goto https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1 in your browser.\r\n\r\n<!--A clear and concise description of what you expected to happen.-->\r\n\r\nIt should have returned the best update for period 484. The Goerli network is current on period 526, so the best update here should exist.\r\n\r\n<!--Steps to reproduce the behavior:\r\n1. Go to '...'\r\n2. Click on '....'\r\n3. Scroll down to '....'\r\n4. See error\r\n-->\r\n\r\nSimply goto https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1 in your browser. The error I get is:\r\n\r\n```\r\nHttpError: Internal Server Error: No partialUpdate available for period 484\r\n    at HttpClient.requestWithBody (/home/john/zk-light-client/operator/node_modules/@lodestar/api/src/utils/client/httpClient.ts:258:15)\r\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\r\n    at HttpClient.json (/home/john/zk-light-client/operator/node_modules/@lodestar/api/src/utils/client/httpClient.ts:128:12)\r\n    at Object.request (/home/john/zk-light-client/operator/node_modules/@lodestar/api/src/utils/client/client.ts:75:21)\r\n    at main (/home/john/zk-light-client/operator/src/helper/step.ts:32:28) {\r\n  status: 500,\r\n  url: 'https://lodestar-goerli.chainsafe.io/eth/v1/beacon/light_client/updates?start_period=484&count=1'\r\n}\r\n```\r\n",
  "closed_by": {
    "login": "dapplion",
    "id": 35266934,
    "node_id": "MDQ6VXNlcjM1MjY2OTM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dapplion",
    "html_url": "https://github.com/dapplion",
    "followers_url": "https://api.github.com/users/dapplion/followers",
    "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
    "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
    "organizations_url": "https://api.github.com/users/dapplion/orgs",
    "repos_url": "https://api.github.com/users/dapplion/repos",
    "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dapplion/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1312633986",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4763#issuecomment-1312633986",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
    "id": 1312633986,
    "node_id": "IC_kwDOCD5_Gc5OPTSC",
    "user": {
      "login": "wemeetagain",
      "id": 1348242,
      "node_id": "MDQ6VXNlcjEzNDgyNDI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1348242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wemeetagain",
      "html_url": "https://github.com/wemeetagain",
      "followers_url": "https://api.github.com/users/wemeetagain/followers",
      "following_url": "https://api.github.com/users/wemeetagain/following{/other_user}",
      "gists_url": "https://api.github.com/users/wemeetagain/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wemeetagain/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wemeetagain/subscriptions",
      "organizations_url": "https://api.github.com/users/wemeetagain/orgs",
      "repos_url": "https://api.github.com/users/wemeetagain/repos",
      "events_url": "https://api.github.com/users/wemeetagain/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wemeetagain/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-13T04:05:03Z",
    "updated_at": "2022-11-13T04:05:03Z",
    "author_association": "MEMBER",
    "body": "We had to resync our public nodes last week, and they're still syncing :(\r\n\r\n```\r\n$ curl https://lodestar-goerli.chainsafe.io/eth/v1/node/syncing\r\n{\"data\":{\"head_slot\":\"868031\",\"sync_distance\":\"3448992\",\"is_syncing\":true,\"is_optimistic\":false}}\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1312633986/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1314539727",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4763#issuecomment-1314539727",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
    "id": 1314539727,
    "node_id": "IC_kwDOCD5_Gc5OWkjP",
    "user": {
      "login": "jtguibas",
      "id": 25734765,
      "node_id": "MDQ6VXNlcjI1NzM0NzY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/25734765?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jtguibas",
      "html_url": "https://github.com/jtguibas",
      "followers_url": "https://api.github.com/users/jtguibas/followers",
      "following_url": "https://api.github.com/users/jtguibas/following{/other_user}",
      "gists_url": "https://api.github.com/users/jtguibas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jtguibas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jtguibas/subscriptions",
      "organizations_url": "https://api.github.com/users/jtguibas/orgs",
      "repos_url": "https://api.github.com/users/jtguibas/repos",
      "events_url": "https://api.github.com/users/jtguibas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jtguibas/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-14T23:23:39Z",
    "updated_at": "2022-11-14T23:23:39Z",
    "author_association": "NONE",
    "body": "Actually, I don't think that this is the reason for the issue. I have my own node running that claims that the sync distance is 0. I still get the same error.\r\n\r\nFurthermore, if it were just a syncing issue, partial updates for early periods should be available, but they are not.",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1314539727/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1314926852",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4763#issuecomment-1314926852",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
    "id": 1314926852,
    "node_id": "IC_kwDOCD5_Gc5OYDEE",
    "user": {
      "login": "hujw77",
      "id": 6929585,
      "node_id": "MDQ6VXNlcjY5Mjk1ODU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6929585?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hujw77",
      "html_url": "https://github.com/hujw77",
      "followers_url": "https://api.github.com/users/hujw77/followers",
      "following_url": "https://api.github.com/users/hujw77/following{/other_user}",
      "gists_url": "https://api.github.com/users/hujw77/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hujw77/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hujw77/subscriptions",
      "organizations_url": "https://api.github.com/users/hujw77/orgs",
      "repos_url": "https://api.github.com/users/hujw77/repos",
      "events_url": "https://api.github.com/users/hujw77/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hujw77/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-15T08:00:10Z",
    "updated_at": "2022-11-15T08:00:10Z",
    "author_association": "NONE",
    "body": "> We had to resync our public nodes last week, and they're still syncing :(\r\n> \r\n> ```\r\n> $ curl https://lodestar-goerli.chainsafe.io/eth/v1/node/syncing\r\n> {\"data\":{\"head_slot\":\"868031\",\"sync_distance\":\"3448992\",\"is_syncing\":true,\"is_optimistic\":false}}\r\n> ```\r\n\r\nMay I ask why you need to re-sync lodestar? because I also run a lodestar node.",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1314926852/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1315314771",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4763#issuecomment-1315314771",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
    "id": 1315314771,
    "node_id": "IC_kwDOCD5_Gc5OZhxT",
    "user": {
      "login": "philknows",
      "id": 58080811,
      "node_id": "MDQ6VXNlcjU4MDgwODEx",
      "avatar_url": "https://avatars.githubusercontent.com/u/58080811?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/philknows",
      "html_url": "https://github.com/philknows",
      "followers_url": "https://api.github.com/users/philknows/followers",
      "following_url": "https://api.github.com/users/philknows/following{/other_user}",
      "gists_url": "https://api.github.com/users/philknows/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/philknows/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/philknows/subscriptions",
      "organizations_url": "https://api.github.com/users/philknows/orgs",
      "repos_url": "https://api.github.com/users/philknows/repos",
      "events_url": "https://api.github.com/users/philknows/events{/privacy}",
      "received_events_url": "https://api.github.com/users/philknows/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-15T13:30:55Z",
    "updated_at": "2022-11-15T13:31:05Z",
    "author_association": "MEMBER",
    "body": "> May I ask why you need to re-sync lodestar? because I also run a lodestar node.\r\n\r\nIt is due to #4702 which changes the way light client updates are stored. So we had to resync the database since the v1.2.x upgrade.",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1315314771/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 1,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1326939118",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4763#issuecomment-1326939118",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
    "id": 1326939118,
    "node_id": "IC_kwDOCD5_Gc5PF3vu",
    "user": {
      "login": "hujw77",
      "id": 6929585,
      "node_id": "MDQ6VXNlcjY5Mjk1ODU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6929585?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hujw77",
      "html_url": "https://github.com/hujw77",
      "followers_url": "https://api.github.com/users/hujw77/followers",
      "following_url": "https://api.github.com/users/hujw77/following{/other_user}",
      "gists_url": "https://api.github.com/users/hujw77/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hujw77/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hujw77/subscriptions",
      "organizations_url": "https://api.github.com/users/hujw77/orgs",
      "repos_url": "https://api.github.com/users/hujw77/repos",
      "events_url": "https://api.github.com/users/hujw77/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hujw77/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-25T01:42:59Z",
    "updated_at": "2022-11-25T01:43:34Z",
    "author_association": "NONE",
    "body": "@philknows May I ask why the lodestar mainnet node re-sync again? I notice the syncing.\r\n```sh\r\n~ curl https://lodestar-mainnet.chainsafe.io/eth/v1/node/syncing\r\n{\"data\":{\"head_slot\":\"1758802\",\"sync_distance\":\"3450913\",\"is_syncing\":true,\"is_optimistic\":false}}⏎\r\n```",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1326939118/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1327032855",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4763#issuecomment-1327032855",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
    "id": 1327032855,
    "node_id": "IC_kwDOCD5_Gc5PGOoX",
    "user": {
      "login": "philknows",
      "id": 58080811,
      "node_id": "MDQ6VXNlcjU4MDgwODEx",
      "avatar_url": "https://avatars.githubusercontent.com/u/58080811?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/philknows",
      "html_url": "https://github.com/philknows",
      "followers_url": "https://api.github.com/users/philknows/followers",
      "following_url": "https://api.github.com/users/philknows/following{/other_user}",
      "gists_url": "https://api.github.com/users/philknows/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/philknows/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/philknows/subscriptions",
      "organizations_url": "https://api.github.com/users/philknows/orgs",
      "repos_url": "https://api.github.com/users/philknows/repos",
      "events_url": "https://api.github.com/users/philknows/events{/privacy}",
      "received_events_url": "https://api.github.com/users/philknows/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-11-25T05:22:59Z",
    "updated_at": "2022-11-25T05:22:59Z",
    "author_association": "MEMBER",
    "body": "> @philknows May I ask why the lodestar mainnet node re-sync again? I notice the syncing.\r\n> \r\n> ```shell\r\n> ~ curl https://lodestar-mainnet.chainsafe.io/eth/v1/node/syncing\r\n> {\"data\":{\"head_slot\":\"1758802\",\"sync_distance\":\"3450913\",\"is_syncing\":true,\"is_optimistic\":false}}⏎\r\n> ```\r\n\r\nIt's still syncing from previously. Hasn't completed yet as far as I'm aware. I'm going to get one of our devops to take a further look into this. ",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1327032855/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1566684372",
    "html_url": "https://github.com/ChainSafe/lodestar/issues/4763#issuecomment-1566684372",
    "issue_url": "https://api.github.com/repos/ChainSafe/lodestar/issues/4763",
    "id": 1566684372,
    "node_id": "IC_kwDOCD5_Gc5dYbTU",
    "user": {
      "login": "dapplion",
      "id": 35266934,
      "node_id": "MDQ6VXNlcjM1MjY2OTM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/35266934?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dapplion",
      "html_url": "https://github.com/dapplion",
      "followers_url": "https://api.github.com/users/dapplion/followers",
      "following_url": "https://api.github.com/users/dapplion/following{/other_user}",
      "gists_url": "https://api.github.com/users/dapplion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dapplion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dapplion/subscriptions",
      "organizations_url": "https://api.github.com/users/dapplion/orgs",
      "repos_url": "https://api.github.com/users/dapplion/repos",
      "events_url": "https://api.github.com/users/dapplion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dapplion/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-05-29T07:26:41Z",
    "updated_at": "2023-05-29T07:26:41Z",
    "author_association": "MEMBER",
    "body": "Closing issues for specific incidents on old versions of Lodestar, please re-open if it happens with latest stable\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/ChainSafe/lodestar/issues/comments/1566684372/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
