{
  "url": "https://api.github.com/repos/foundry-rs/foundry/issues/2943",
  "repository_url": "https://api.github.com/repos/foundry-rs/foundry",
  "labels_url": "https://api.github.com/repos/foundry-rs/foundry/issues/2943/labels{/name}",
  "comments_url": "https://api.github.com/repos/foundry-rs/foundry/issues/2943/comments",
  "events_url": "https://api.github.com/repos/foundry-rs/foundry/issues/2943/events",
  "html_url": "https://github.com/foundry-rs/foundry/issues/2943",
  "id": 1351207195,
  "node_id": "I_kwDOGBlvNc5Qickb",
  "number": 2943,
  "title": "Unexpected Revert on Test",
  "user": {
    "login": "bthreader",
    "id": 62354395,
    "node_id": "MDQ6VXNlcjYyMzU0Mzk1",
    "avatar_url": "https://avatars.githubusercontent.com/u/62354395?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bthreader",
    "html_url": "https://github.com/bthreader",
    "followers_url": "https://api.github.com/users/bthreader/followers",
    "following_url": "https://api.github.com/users/bthreader/following{/other_user}",
    "gists_url": "https://api.github.com/users/bthreader/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bthreader/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bthreader/subscriptions",
    "organizations_url": "https://api.github.com/users/bthreader/orgs",
    "repos_url": "https://api.github.com/users/bthreader/repos",
    "events_url": "https://api.github.com/users/bthreader/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bthreader/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 3334394228,
      "node_id": "MDU6TGFiZWwzMzM0Mzk0MjI4",
      "url": "https://api.github.com/repos/foundry-rs/foundry/labels/T-bug",
      "name": "T-bug",
      "color": "d73a4a",
      "default": false,
      "description": "Type: bug"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2022-08-25T17:07:44Z",
  "updated_at": "2022-08-25T19:34:41Z",
  "closed_at": "2022-08-25T19:34:41Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "### Component\n\nForge\n\n### Have you ensured that all of these are up to date?\n\n- [X] Foundry\n- [ ] Foundryup\n\n### What version of Foundry are you on?\n\nforge 0.2.0 (66ef1ae 2022-08-11T15:42:20.650087337Z)\n\n### What command(s) is the bug in?\n\ntest\n\n### Operating System\n\nLinux\n\n### Describe the bug\n\nReverting on a transfer command on a very simple contract. The contract is basically just a bank account where anyone can \"topup\" or \"withdraw\" from the balance:\r\n\r\n```\r\ncontract Example {\r\n\r\n    function topUp() external payable {}\r\n\r\n    function withdraw(uint256 amount) external {\r\n        require(\r\n            amount <= address(this).balance,\r\n            \"Cannot withdraw more than is within the contract\"\r\n        );\r\n        \r\n        payable(msg.sender).transfer(amount);\r\n    }\r\n}\r\n```\r\n\r\nThis is the test:\r\n\r\n```\r\ncontract ExampleTest is Test {\r\n\r\n    Example public account;\r\n    address public acc1;\r\n\r\n    constructor () {\r\n        acc1 = address(0x1);\r\n        account = new Example();\r\n    }\r\n\r\n    function testItWorks() public {\r\n        vm.deal(acc1, 25);\r\n        vm.startPrank(acc1);\r\n        account.topUp{ value : 25 }();\r\n        account.withdraw(25);\r\n        vm.stopPrank();\r\n    }\r\n}\r\n```\r\n\r\naccount.withdraw causes a reversion (unexpected), here are the traces:\r\n\r\n```\r\nTraces:\r\n  [52308] ExampleTest::testItWorks() \r\n    ├─ [0] VM::deal(0x0000000000000000000000000000000000000001, 25) \r\n    │   └─ ← ()\r\n    ├─ [0] VM::startPrank(0x0000000000000000000000000000000000000001) \r\n    │   └─ ← ()\r\n    ├─ [96] Example::topUp{value: 25}() \r\n    │   └─ ← ()\r\n    ├─ [34422] Example::withdraw(25) \r\n    │   ├─ [0] PRECOMPILE::ecrecover{value: 25}() \r\n    │   │   └─ ← \r\n    │   └─ ← \"EvmError: Revert\"\r\n    └─ ← \"EvmError: Revert\"\r\n```\r\n\r\n I have tried running with --debug but cannot seem to find what's causing the issue. I have deployed the contract and it works as expected. I'm confused because I have implemented similar functionality in other contracts and testing has gone fine.\r\n\r\nPlease let me know if I have made any errors with my testing and/or writing the contract.\r\n\r\nThanks,\r\nBen",
  "closed_by": {
    "login": "onbjerg",
    "id": 8862627,
    "node_id": "MDQ6VXNlcjg4NjI2Mjc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8862627?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/onbjerg",
    "html_url": "https://github.com/onbjerg",
    "followers_url": "https://api.github.com/users/onbjerg/followers",
    "following_url": "https://api.github.com/users/onbjerg/following{/other_user}",
    "gists_url": "https://api.github.com/users/onbjerg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/onbjerg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/onbjerg/subscriptions",
    "organizations_url": "https://api.github.com/users/onbjerg/orgs",
    "repos_url": "https://api.github.com/users/onbjerg/repos",
    "events_url": "https://api.github.com/users/onbjerg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/onbjerg/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/2943/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/foundry-rs/foundry/issues/2943/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1227681135",
    "html_url": "https://github.com/foundry-rs/foundry/issues/2943#issuecomment-1227681135",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/2943",
    "id": 1227681135,
    "node_id": "IC_kwDOGBlvNc5JLO1v",
    "user": {
      "login": "onbjerg",
      "id": 8862627,
      "node_id": "MDQ6VXNlcjg4NjI2Mjc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8862627?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/onbjerg",
      "html_url": "https://github.com/onbjerg",
      "followers_url": "https://api.github.com/users/onbjerg/followers",
      "following_url": "https://api.github.com/users/onbjerg/following{/other_user}",
      "gists_url": "https://api.github.com/users/onbjerg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/onbjerg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/onbjerg/subscriptions",
      "organizations_url": "https://api.github.com/users/onbjerg/orgs",
      "repos_url": "https://api.github.com/users/onbjerg/repos",
      "events_url": "https://api.github.com/users/onbjerg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/onbjerg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-08-25T19:34:41Z",
    "updated_at": "2022-08-25T19:34:41Z",
    "author_association": "MEMBER",
    "body": "You can't use `address(n)` where `n <= 10` since those are precompile addresses.",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1227681135/reactions",
      "total_count": 4,
      "+1": 4,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
