{
  "url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
  "repository_url": "https://api.github.com/repos/foundry-rs/foundry",
  "labels_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154/labels{/name}",
  "comments_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154/comments",
  "events_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154/events",
  "html_url": "https://github.com/foundry-rs/foundry/issues/6154",
  "id": 1966275289,
  "node_id": "I_kwDOGBlvNc51MvrZ",
  "number": 6154,
  "title": "Scripting borked: No such file or directory (os error 2)",
  "user": {
    "login": "robriks",
    "id": 80549215,
    "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
    "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/robriks",
    "html_url": "https://github.com/robriks",
    "followers_url": "https://api.github.com/users/robriks/followers",
    "following_url": "https://api.github.com/users/robriks/following{/other_user}",
    "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
    "organizations_url": "https://api.github.com/users/robriks/orgs",
    "repos_url": "https://api.github.com/users/robriks/repos",
    "events_url": "https://api.github.com/users/robriks/events{/privacy}",
    "received_events_url": "https://api.github.com/users/robriks/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 3334394228,
      "node_id": "MDU6TGFiZWwzMzM0Mzk0MjI4",
      "url": "https://api.github.com/repos/foundry-rs/foundry/labels/T-bug",
      "name": "T-bug",
      "color": "d73a4a",
      "default": false,
      "description": "Type: bug"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 12,
  "created_at": "2023-10-27T22:47:23Z",
  "updated_at": "2023-11-06T21:03:24Z",
  "closed_at": "2023-11-06T21:03:24Z",
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "### Component\r\n\r\nForge\r\n\r\n### Have you ensured that all of these are up to date?\r\n\r\n- [X] Foundry\r\n- [X] Foundryup\r\n\r\n### What version of Foundry are you on?\r\n\r\nforge 0.2.0 (602460e 2023-10-24T00:16:58.926357929Z)\r\n\r\n### What command(s) is the bug in?\r\n\r\nforge script\r\n\r\n### Operating System\r\n\r\nLinux\r\n\r\n### Describe the bug\r\n\r\nRunning `forge script` has started to fail with error \"No such file or directory (os error 2)\" and I am not sure why.\r\n\r\nFor example, ` forge script script/accountGroup/AccountGroup.s.sol` on a file that definitely exists (see screenshot) fails.\r\n\r\n![image](https://github.com/foundry-rs/foundry/assets/80549215/59b7ebd4-1190-4eb3-9753-b1bbc6e48972)\r\n\r\nRelevant items that I have investigated to no avail:\r\n- Deleting `../.svm` worked once, but I can no longer use this fix since the .svm file is either no longer being generated or only worked the first time. Have had trouble finding documentation around the .svm file and what generates it. I feel like it is the strongest lead since nuking it fixed the problem once\r\n- Installing z3 prover theorem did not help (problem started on an Ubuntu VM running on Apple M1 silicon, not sure if it is relevant)\r\n- Downloading Solc binary from solc-bin repository and using the local binary did not help\r\n- Cloning the repository to a new environment (cpu architecture, OS) worked for a bit but begins to fail similarly within a day (usually when `forge build --force` or `forge update` is invoked). I discovered this by switching to Ubuntu WSL running on Windows 10, which worked briefly before borking. Same for switching to Ubuntu 22.04 desktop on AMD64.\r\n- There is a file I am reading from using `vm.readFile()` that sometimes doesn't exist, but for months it had given a more verbose warning reminding me to create the file and not caused any issues of this scale. The os error 2 warning is different, and creating the file in both the 0xRails git submodule and the GroupOS parent repository does not resolve the error\r\n- Attempted purging all submodules and re-adding them using `forge install purged_submodule` did not make a difference\r\n- Tried ensuring remappings from submodules do not overwrite by using declarations in remappings.txt like `src/=src/` and `test/=test/` etc\r\n\r\nCan provide a reference branch to reproduce this issue, but I need to make some changes first.\r\n\r\nPlease help, I am running out of leads to investigate! I feel like the .svm and the git submodule leads are most relevant since I confirmed issues WRT both, but resolving them does not fix the problem.\r\n\r\nPossibly related? `forge update` fails with errors caused by submodule dependencies like the below:\r\n`fatal: Needed a single revision\r\nfatal: Unable to find current origin/v1.3.0 revision in submodule path 'lib/forge-std'\r\nfatal: Needed a single revision\r\nfatal: Unable to find current origin/v4.9.3 revision in submodule path 'lib/openzeppelin-contracts'\r\nfatal: Needed a single revision\r\nfatal: Unable to find current origin/v0.3.1 revision in submodule path 'lib/erc6551'`",
  "closed_by": {
    "login": "robriks",
    "id": 80549215,
    "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
    "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/robriks",
    "html_url": "https://github.com/robriks",
    "followers_url": "https://api.github.com/users/robriks/followers",
    "following_url": "https://api.github.com/users/robriks/following{/other_user}",
    "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
    "organizations_url": "https://api.github.com/users/robriks/orgs",
    "repos_url": "https://api.github.com/users/robriks/repos",
    "events_url": "https://api.github.com/users/robriks/events{/privacy}",
    "received_events_url": "https://api.github.com/users/robriks/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
[
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783594355",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1783594355",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1783594355,
    "node_id": "IC_kwDOGBlvNc5qT31z",
    "user": {
      "login": "mattsse",
      "id": 19890894,
      "node_id": "MDQ6VXNlcjE5ODkwODk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19890894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mattsse",
      "html_url": "https://github.com/mattsse",
      "followers_url": "https://api.github.com/users/mattsse/followers",
      "following_url": "https://api.github.com/users/mattsse/following{/other_user}",
      "gists_url": "https://api.github.com/users/mattsse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mattsse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mattsse/subscriptions",
      "organizations_url": "https://api.github.com/users/mattsse/orgs",
      "repos_url": "https://api.github.com/users/mattsse/repos",
      "events_url": "https://api.github.com/users/mattsse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mattsse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-27T22:57:55Z",
    "updated_at": "2023-10-27T22:57:55Z",
    "author_association": "MEMBER",
    "body": "thanks for looking into this.\r\n\r\nis this public by any chance?\r\n\r\ncan you charge the logs that you get from running with RUST_LOG like `RUST_LOG=trace forge ...`?",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783594355/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783595001",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1783595001",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1783595001,
    "node_id": "IC_kwDOGBlvNc5qT3_5",
    "user": {
      "login": "mattsse",
      "id": 19890894,
      "node_id": "MDQ6VXNlcjE5ODkwODk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19890894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mattsse",
      "html_url": "https://github.com/mattsse",
      "followers_url": "https://api.github.com/users/mattsse/followers",
      "following_url": "https://api.github.com/users/mattsse/following{/other_user}",
      "gists_url": "https://api.github.com/users/mattsse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mattsse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mattsse/subscriptions",
      "organizations_url": "https://api.github.com/users/mattsse/orgs",
      "repos_url": "https://api.github.com/users/mattsse/repos",
      "events_url": "https://api.github.com/users/mattsse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mattsse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-27T22:59:03Z",
    "updated_at": "2023-10-27T22:59:03Z",
    "author_association": "MEMBER",
    "body": "can you also try after foundryup, we fixed a few issues the last few days.\r\n\r\nsorry for the inconveniences ",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783595001/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783859146",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1783859146",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1783859146,
    "node_id": "IC_kwDOGBlvNc5qU4fK",
    "user": {
      "login": "robriks",
      "id": 80549215,
      "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robriks",
      "html_url": "https://github.com/robriks",
      "followers_url": "https://api.github.com/users/robriks/followers",
      "following_url": "https://api.github.com/users/robriks/following{/other_user}",
      "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
      "organizations_url": "https://api.github.com/users/robriks/orgs",
      "repos_url": "https://api.github.com/users/robriks/repos",
      "events_url": "https://api.github.com/users/robriks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robriks/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-28T16:09:10Z",
    "updated_at": "2023-10-28T16:37:08Z",
    "author_association": "CONTRIBUTOR",
    "body": "Yeah of course! `foundryup` does not fix the issue. Here are the `RUST_LOG=trace` outputs, unfortunately there are so many that my terminal cannot fit all of them so it is truncated. If you need more of the logs I can try to find a way to modify my terminal to fit and copy paste the entirety of it.\r\n\r\nI think the traces at the end of the logs are probably what we are after anyway. I can also pass the `--force` flag for more info or provide the `solidity-files-cache.json` file if that is helpful.\r\n\r\n[RustTraceLogs.txt](https://github.com/foundry-rs/foundry/files/13196244/RustTraceLogs.txt)\r\n\r\nNote that this is the output when run from the Ubuntu on WSL (AMD64 arch) setup. ",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783859146/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783872391",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1783872391",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1783872391,
    "node_id": "IC_kwDOGBlvNc5qU7uH",
    "user": {
      "login": "mattsse",
      "id": 19890894,
      "node_id": "MDQ6VXNlcjE5ODkwODk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19890894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mattsse",
      "html_url": "https://github.com/mattsse",
      "followers_url": "https://api.github.com/users/mattsse/followers",
      "following_url": "https://api.github.com/users/mattsse/following{/other_user}",
      "gists_url": "https://api.github.com/users/mattsse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mattsse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mattsse/subscriptions",
      "organizations_url": "https://api.github.com/users/mattsse/orgs",
      "repos_url": "https://api.github.com/users/mattsse/repos",
      "events_url": "https://api.github.com/users/mattsse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mattsse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-28T17:06:09Z",
    "updated_at": "2023-10-28T17:06:09Z",
    "author_association": "MEMBER",
    "body": "hmm, I believe this is a linking bug, but hard to debug/fix without a proper way to reproduce...\r\n\r\ncould you perhaps try:\r\n* updating all submodules: `git submodule update --init --recursive`\r\n* `forge clean`\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783872391/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783898522",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1783898522",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1783898522,
    "node_id": "IC_kwDOGBlvNc5qVCGa",
    "user": {
      "login": "robriks",
      "id": 80549215,
      "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robriks",
      "html_url": "https://github.com/robriks",
      "followers_url": "https://api.github.com/users/robriks/followers",
      "following_url": "https://api.github.com/users/robriks/following{/other_user}",
      "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
      "organizations_url": "https://api.github.com/users/robriks/orgs",
      "repos_url": "https://api.github.com/users/robriks/repos",
      "events_url": "https://api.github.com/users/robriks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robriks/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-28T19:01:27Z",
    "updated_at": "2023-10-28T19:01:27Z",
    "author_association": "CONTRIBUTOR",
    "body": "Unfortunately that did not fix the bug, still getting \"No such file or directory (os error 2)\"\r\n\r\nA linking bug would make sense as the nuking .svm file solution I found was taken from the NixOS thread below, which appears to be a similar issue though I am not using NixOS or a FHS-challenged Linux distro. The fact that I use Ubuntu VMs on both WSL and Apple M1 silicon seems similar enough, but what is confusing is that now the error is appearing on a plain jane Ubuntu AMD64 architecture desktop and vanilla MacOS on M1.\r\nhttps://github.com/foundry-rs/foundry/issues/545\r\n\r\nI piped the entire output of the `forge script` command into the file below in case the truncated output was not enough information.\r\n\r\n[RustTraceLogs.txt](https://github.com/foundry-rs/foundry/files/13196529/RustTraceLogs.txt)\r\n\r\nIf these are not enough information to properly debug, I will provide a reproducible branch for you to examine. At the moment one submodule is private so I'd just need to remove that one and delete references to it\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1783898522/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785308417",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1785308417",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1785308417,
    "node_id": "IC_kwDOGBlvNc5qaaUB",
    "user": {
      "login": "robriks",
      "id": 80549215,
      "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robriks",
      "html_url": "https://github.com/robriks",
      "followers_url": "https://api.github.com/users/robriks/followers",
      "following_url": "https://api.github.com/users/robriks/following{/other_user}",
      "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
      "organizations_url": "https://api.github.com/users/robriks/orgs",
      "repos_url": "https://api.github.com/users/robriks/repos",
      "events_url": "https://api.github.com/users/robriks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robriks/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-30T14:13:25Z",
    "updated_at": "2023-10-30T14:13:25Z",
    "author_association": "CONTRIBUTOR",
    "body": "@mattsse  I've reconfigured the repository for debugging purposes so the problem is directly reproducible. Your help is deeply appreciated as I don't know what else to do. Here is the repository:\r\n\r\nhttps://github.com/0xStation/groupos/tree/linking-bug\r\n\r\nThe branch I've configured for debugging is called `linking-bug` so once cloned, be sure to git checkout linking-bug. Then you can see the error for yourself by running:\r\n\r\n`forge script script/token/NewChain.s.sol --force`\r\n\r\nI believe the `--force` flag is required to trigger the bug.\r\n\r\nOne thing to note is that `forge script` works when run from a submodule directory:\r\n`cd lib/0xrails`\r\n`forge script script/AccountProxy.s.sol`",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785308417/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785499986",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1785499986",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1785499986,
    "node_id": "IC_kwDOGBlvNc5qbJFS",
    "user": {
      "login": "mattsse",
      "id": 19890894,
      "node_id": "MDQ6VXNlcjE5ODkwODk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19890894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mattsse",
      "html_url": "https://github.com/mattsse",
      "followers_url": "https://api.github.com/users/mattsse/followers",
      "following_url": "https://api.github.com/users/mattsse/following{/other_user}",
      "gists_url": "https://api.github.com/users/mattsse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mattsse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mattsse/subscriptions",
      "organizations_url": "https://api.github.com/users/mattsse/orgs",
      "repos_url": "https://api.github.com/users/mattsse/repos",
      "events_url": "https://api.github.com/users/mattsse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mattsse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-30T15:44:45Z",
    "updated_at": "2023-10-30T15:44:45Z",
    "author_association": "MEMBER",
    "body": "unable to compile this because\r\n\r\n https://github.com/0xStation/protocol-ops is private",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785499986/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785541325",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1785541325",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1785541325,
    "node_id": "IC_kwDOGBlvNc5qbTLN",
    "user": {
      "login": "robriks",
      "id": 80549215,
      "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robriks",
      "html_url": "https://github.com/robriks",
      "followers_url": "https://api.github.com/users/robriks/followers",
      "following_url": "https://api.github.com/users/robriks/following{/other_user}",
      "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
      "organizations_url": "https://api.github.com/users/robriks/orgs",
      "repos_url": "https://api.github.com/users/robriks/repos",
      "events_url": "https://api.github.com/users/robriks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robriks/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-30T16:04:52Z",
    "updated_at": "2023-10-30T16:04:52Z",
    "author_association": "CONTRIBUTOR",
    "body": "Thanks for the quick support!\r\n\r\nI thought I removed it from both the host repository and the 0xRails submodule in the `linking-bug` branch. \r\n\r\nIs it still present for you in the GroupOS `linking-bug` branch (commit e1b1a28)? Or is it still present for you in the 0xRails submodule (commit 2a77ba9)? Sorry for the issue.",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785541325/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785929501",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1785929501",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1785929501,
    "node_id": "IC_kwDOGBlvNc5qcx8d",
    "user": {
      "login": "mattsse",
      "id": 19890894,
      "node_id": "MDQ6VXNlcjE5ODkwODk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/19890894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mattsse",
      "html_url": "https://github.com/mattsse",
      "followers_url": "https://api.github.com/users/mattsse/followers",
      "following_url": "https://api.github.com/users/mattsse/following{/other_user}",
      "gists_url": "https://api.github.com/users/mattsse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mattsse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mattsse/subscriptions",
      "organizations_url": "https://api.github.com/users/mattsse/orgs",
      "repos_url": "https://api.github.com/users/mattsse/repos",
      "events_url": "https://api.github.com/users/mattsse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mattsse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-10-30T19:48:47Z",
    "updated_at": "2023-10-30T19:48:47Z",
    "author_association": "MEMBER",
    "body": "ptal @Evalir ",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1785929501/reactions",
      "total_count": 1,
      "+1": 1,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1793088615",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1793088615",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1793088615,
    "node_id": "IC_kwDOGBlvNc5q4Fxn",
    "user": {
      "login": "robriks",
      "id": 80549215,
      "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robriks",
      "html_url": "https://github.com/robriks",
      "followers_url": "https://api.github.com/users/robriks/followers",
      "following_url": "https://api.github.com/users/robriks/following{/other_user}",
      "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
      "organizations_url": "https://api.github.com/users/robriks/orgs",
      "repos_url": "https://api.github.com/users/robriks/repos",
      "events_url": "https://api.github.com/users/robriks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robriks/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-11-03T20:57:10Z",
    "updated_at": "2023-11-03T20:57:10Z",
    "author_association": "CONTRIBUTOR",
    "body": "Sorry to bother, @Evalir, but is there any updates on this? \r\n\r\nI have been using `forge flatten` to collect the files required for running my scripts and then running them in a different directory as a workaround but I would love to be able to use `forge script` again.",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1793088615/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1796403885",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1796403885",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1796403885,
    "node_id": "IC_kwDOGBlvNc5rEvKt",
    "user": {
      "login": "robriks",
      "id": 80549215,
      "node_id": "MDQ6VXNlcjgwNTQ5MjE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/80549215?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/robriks",
      "html_url": "https://github.com/robriks",
      "followers_url": "https://api.github.com/users/robriks/followers",
      "following_url": "https://api.github.com/users/robriks/following{/other_user}",
      "gists_url": "https://api.github.com/users/robriks/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/robriks/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/robriks/subscriptions",
      "organizations_url": "https://api.github.com/users/robriks/orgs",
      "repos_url": "https://api.github.com/users/robriks/repos",
      "events_url": "https://api.github.com/users/robriks/events{/privacy}",
      "received_events_url": "https://api.github.com/users/robriks/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-11-06T20:43:52Z",
    "updated_at": "2023-11-06T20:43:52Z",
    "author_association": "CONTRIBUTOR",
    "body": "Good news! I seem to have found the offending file, though I have not yet identified the exact problem.\r\n\r\nFor context, there was a submodule dependency that was using both HardHat and Foundry, so the `remappings.txt` in the submodule had declared OpenZeppelin using the Hardhat syntax: `@openzeppelin/=lib/openzeppelin-contracts/` This was causing some confusion and opacity of compiler errors, only printing \"No such file or directory (os error 2)\" to the console when running `forge script`. Once I removed that submodule, the compiler error became much more informative:\r\n\r\n![image](https://github.com/foundry-rs/foundry/assets/80549215/fadfdc31-8957-48b6-98e1-f8b6dcb05635)\r\n\r\nWhat's interesting is that the ERC4337  file causing the problem is one that doesn't contain any contract declaration; only a struct. It's also worth noting that the struct declaration uses the name `struct UserOperation { ... }` which is also the same name as the file: \"UserOperation.sol\"\r\n\r\nPerhaps Foundry or Solc is expecting to find a contract artifact instead of a lonely struct, or perhaps the lonely struct is not expected to share the same name of the file without a contract. Another thing I can't explain is that simply upgrading the pragma version declaration from `^0.8.13` to `^0.8.19` seems to have cleared up the issue.\r\n\r\nI'm relieved to have scripts working again and am hoping this information is enough to help you identify the source of the bug. Let me know if there's any more I can do to help.",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1796403885/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 1,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1796426602",
    "html_url": "https://github.com/foundry-rs/foundry/issues/6154#issuecomment-1796426602",
    "issue_url": "https://api.github.com/repos/foundry-rs/foundry/issues/6154",
    "id": 1796426602,
    "node_id": "IC_kwDOGBlvNc5rE0tq",
    "user": {
      "login": "Evalir",
      "id": 26014927,
      "node_id": "MDQ6VXNlcjI2MDE0OTI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/26014927?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Evalir",
      "html_url": "https://github.com/Evalir",
      "followers_url": "https://api.github.com/users/Evalir/followers",
      "following_url": "https://api.github.com/users/Evalir/following{/other_user}",
      "gists_url": "https://api.github.com/users/Evalir/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Evalir/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Evalir/subscriptions",
      "organizations_url": "https://api.github.com/users/Evalir/orgs",
      "repos_url": "https://api.github.com/users/Evalir/repos",
      "events_url": "https://api.github.com/users/Evalir/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Evalir/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2023-11-06T21:01:00Z",
    "updated_at": "2023-11-06T21:01:57Z",
    "author_association": "MEMBER",
    "body": "Yep @robriks, glad to hear scripts are working for you again!\r\n\r\nI spent some time looking at the issue today, and this is a combination of dependencies having either outdated or extremely complicated remappings, and also a bug on our side in `foundry-rs/compilers` (https://github.com/foundry-rs/compilers/issues/9). We're working on resolving the `compilers` bug. It's definitely the first time I see the pragma affecting compilation though.\r\n\r\nWondering if we can close this, to track on compilers?",
    "reactions": {
      "url": "https://api.github.com/repos/foundry-rs/foundry/issues/comments/1796426602/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 1,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
